#!/usr/bin/env bash
# Stage a pico-sdk-lite bundle for the browser IDE. Harvests pre-compiled
# .o files (from arm-none-eabi-gcc) out of firmware/build/, plus startup
# objects, the preprocessed linker script, and the SDK public headers
# tree. Packages everything under web/assets/sdk/ where compiler.js can
# fetch and mount it into the WASM VFS.
#
# Requires: `firmware/scripts/build.sh` has been run successfully.
# Run from the repo root:  bash web/lib/build-sdk-bundle.sh
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
FIRMWARE_BUILD="$REPO_ROOT/firmware/build"
OUT="$REPO_ROOT/web/assets/sdk"
PICO_SDK_ROOT="${PICO_SDK_PATH:-$HOME/.pico-sdk/sdk/2.2.0}"

[ -d "$FIRMWARE_BUILD/app/CMakeFiles/pico_poe_app.dir" ] || {
    echo "error: firmware/build missing. Run firmware/scripts/build.sh first."
    exit 1
}
[ -d "$PICO_SDK_ROOT/src" ] || {
    echo "error: Pico SDK not found at $PICO_SDK_ROOT"
    exit 1
}

echo "=== Cleaning $OUT ==="
rm -rf "$OUT"
mkdir -p "$OUT"/{lib,startup,linker,headers}

echo "=== Harvesting pico-sdk core .o files ==="
# Bundle the FULL firmware build so user IDE code can link as a
# supplement (Arduino-hooks: user provides strong pico_poe_setup/loop
# overrides for the weak hooks in firmware's main.c). That requires
# main.c.o, network.c.o, http_server.c.o, ota.c.o, the lwIP stack, the
# RMII driver, tinyUSB, and the SDK modules they pull in. An earlier
# version of this script excluded all of those — that was correct when
# user code was the entire firmware, but the current architecture
# needs them. Bundle size goes from ~1.3 MB to ~3 MB; still trivial.
#
# Keep path structure relative to the CMake .dir root so no name
# collisions between multiple timer.c.o / flash.c.o from different
# sub-modules.
pushd "$FIRMWARE_BUILD/app/CMakeFiles/pico_poe_app.dir" >/dev/null
find . -name '*.o' | tar -cf "$OUT/lib/pico-sdk-objects.tar" -T -
popd >/dev/null
# Count + size
TARN=$(tar -tf "$OUT/lib/pico-sdk-objects.tar" | wc -l | tr -d ' ')
TARSZ=$(stat -f '%z' "$OUT/lib/pico-sdk-objects.tar")
echo "  $TARN objects, $(( TARSZ / 1024 )) KB (tarball)"

echo "=== Startup objects ==="
# bs2 lives at .../boot_stage2/CMakeFiles/bs2_default_library.dir/...S.o
# (~8 directories deep) — drop the maxdepth limit, the build tree is
# bounded enough that an unbounded find finishes in a few ms.
find "$FIRMWARE_BUILD" -name 'bs2_default_padded_checksummed*.o' -exec cp {} "$OUT/startup/" \;
ls -la "$OUT/startup/"

echo "=== Linker scripts ==="
# memmap_default.ld — main script. Take the post-preprocess copy CMake
# produced if available, else fall back to the SDK source.
LD_PREPROCESSED=$(find "$FIRMWARE_BUILD" -name 'memmap_default.ld' 2>/dev/null | head -1)
LD_SOURCE="$PICO_SDK_ROOT/src/rp2_common/pico_crt0/rp2350/memmap_default.ld"
cp "${LD_PREPROCESSED:-$LD_SOURCE}" "$OUT/linker/memmap_default.ld"

# pico_flash_region.ld — generated by pico_set_binary_version() into
# firmware/build/. memmap_default.ld INCLUDEs this for the partition
# table layout, so the IDE link will fail without it (404 fetch error
# in the browser; "cannot find pico_flash_region.ld" from lld).
PFR_GENERATED=$(find "$FIRMWARE_BUILD" -maxdepth 2 -name 'pico_flash_region.ld' 2>/dev/null | head -1)
if [ -n "$PFR_GENERATED" ]; then
    cp "$PFR_GENERATED" "$OUT/linker/pico_flash_region.ld"
else
    echo "warning: pico_flash_region.ld not found in firmware/build/ — IDE link will fail"
fi
ls -la "$OUT/linker/"

echo "=== Public headers tree ==="
# The SDK layout is `src/<category>/<module>/include/<path>.h`. For a single
# `-I <dir>` to satisfy `#include "pico/stdlib.h"` etc, flatten all public
# include/ subdirs into one merged tree at $OUT/headers/include/.
mkdir -p "$OUT/headers/include"
find "$PICO_SDK_ROOT/src" -type d -name include | while read -r inc; do
    # Each inc is like .../src/rp2_common/pico_stdlib/include
    rsync -a "$inc/" "$OUT/headers/include/"
done

# Generated config headers from the CMake build (board/platform selection,
# lwip opts, etc). Keep the board_config headers — lots of SDK code needs them.
# rsync preserving directory structure from the build's generated include.
find "$FIRMWARE_BUILD" -type d \( -name 'generated' -o -name 'pico_base' \) | while read -r d; do
    rsync -a "$d/" "$OUT/headers/include/" 2>/dev/null || true
done

# Also ship a bundled firmware app-level pico_poe_config.h + the user-facing
# pico_poe_user.h (transmit/log/on_command) so user code that wants
# board-specific macros and the IDE API can find them.
if [ -d "$REPO_ROOT/firmware/include" ]; then
    rsync -a "$REPO_ROOT/firmware/include/" "$OUT/headers/include/"
fi

# Browser-only libc shim headers (math.h, stdio.h, etc.) — the firmware
# builds against newlib for arm-none-eabi and doesn't need these, but the
# IDE's WASM-clang compile path resolves <math.h> et al. via these stubs
# (referenced as `-isystem /pico-sdk/include/libc-stubs` in compiler.js).
# Source lives under web/lib/sdk-extras/ so it survives bundle wipes.
if [ -d "$REPO_ROOT/web/lib/sdk-extras" ]; then
    rsync -a "$REPO_ROOT/web/lib/sdk-extras/" "$OUT/headers/include/"
fi

# Rewrite absolute SDK paths in CMake-generated config_autogen.h headers.
# CMake bakes the host's actual install path (e.g. /Users/foo/.pico-sdk
# /sdk/2.2.0/src/.../include/boards/pico2.h) into these files; in the
# IDE's WASM VFS the SDK is mounted at /pico-sdk/include, so the
# absolutes never resolve. Strategy: anywhere we see a quoted include
# whose path goes through .../<module>/include/, drop the prefix down
# to whatever follows include/. The relative tail is what -I /pico-sdk
# /include resolves against. Idempotent (safe to re-run).
echo "=== Rewriting absolute SDK paths in generated headers ==="
ESC_SDK=$(printf '%s' "$PICO_SDK_ROOT" | sed 's/[][\\.*^$/]/\\&/g')
find "$OUT/headers/include" -name 'config_autogen.h' | while read -r f; do
    sed -i.bak "s|\"$ESC_SDK/[^\"]*/include/|\"|g" "$f"
    rm -f "$f.bak"
    if grep -q "$PICO_SDK_ROOT" "$f"; then
        echo "  warning: $f still has absolute paths after rewrite"
    else
        echo "  ✓ $(echo "$f" | sed "s|$OUT/||")"
    fi
done

# Generate the files.txt manifest required by compiler.js (the browser
# can't list directories, so each fetched tree ships an explicit list).
# Sorted for stable diffs across rebuilds.
( cd "$OUT/headers/include" && \
  find . -type f -not -name files.txt | sed 's|^\./||' | LC_ALL=C sort > files.txt )
echo "  manifest: $(wc -l < "$OUT/headers/include/files.txt") header files"

# Boot2 + tinyUSB are absent from this lite bundle; touch stubs so downstream
# #include doesn't explode. Users writing network-heavy code will hit
# missing-symbol errors at link time which is fine — the bundle is sized for
# basic GPIO / stdio demos.

echo "=== Write manifest ==="
cat > "$OUT/manifest.json" <<EOF
{
  "pico_sdk_version": "2.2.0",
  "generator": "firmware/build harvest",
  "pico_board": "pico2",
  "flags": [
    "-target", "thumbv8m.main-none-eabi",
    "-mcpu=cortex-m33",
    "-mthumb",
    "-mfloat-abi=softfp"
  ],
  "linker_script": "/pico-sdk/linker/memmap_default.ld",
  "startup_objects": ["/pico-sdk/startup/bs2_default_padded_checksummed.S.obj"],
  "lib_tarball": "/pico-sdk/lib/pico-sdk-objects.tar",
  "include_root": "/pico-sdk/include",
  "notes": "Harvested from arm-none-eabi-gcc build; lld links GCC-compiled .o files fine. tinyUSB/lwIP excluded — this is a pico-sdk-LITE for GPIO/time/stdio demos."
}
EOF

echo
echo "=== staged ==="
du -sh "$OUT"/*
echo
echo "Total: $(du -sh "$OUT" | awk '{print $1}')"
echo "compiler.js can fetch from $OUT/ at ./assets/sdk/"
