/**
 * Raw TCP HTTP server for CONDUIT.
 *
 * Implements a minimal HTTP/1.1 server using lwIP raw TCP API.
 * Routes:
 *   OPTIONS *           → CORS + Private Network Access preflight
 *   GET  /api/status    → JSON device status
 *   POST /api/upload    → UF2 firmware upload (auth required)
 *   POST /api/reboot    → Controlled reboot (auth required)
 *   *                   → 404
 *
 * All responses include CORS and PNA headers.
 */

#include "http_server.h"
#include "ws_server.h"
#include "network.h"
#include "ota.h"
#include "ota_ring.h"
#include "conduit_config.h"
#include "conduit_version.h"  // generated by configure_file from CMakeLists.txt
#include "dev_log.h"
#include "log_buffer.h"
#include "data_buffer.h"
#include "commands.h"
#include "identity.h"
#include "mbedtls_slab.h"
#include "incident_log.h"
#include "diag.h"
#include "rmii_ethernet/netif.h"

#include "mbedtls/platform.h"
#include "mbedtls/sha1.h"
#include "mbedtls/base64.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "lwip/altcp.h"
#include "lwip/altcp_tcp.h"
#include "lwip/altcp_tls.h"
#include "lwip/tcp.h"           // tcp_pcb fields for keepalive (walked via altcp inner_conn)
#include "lwip/stats.h"         // MEMP_STATS pools for /api/status diag block
#include "lwip/memp.h"          // MEMP_PBUF_POOL / MEMP_TCP_PCB / MEMP_SYS_TIMEOUT indices
#include "lwip/pbuf.h"
#include "pico/unique_id.h"
#include "pico/stdlib.h"
#include "pico/bootrom.h"
#include "boot/picoboot_constants.h"
#include "boot/picobin.h"
#include "hardware/watchdog.h"

// Maximum HTTP header size we'll parse
#define HTTP_MAX_HEADER  2048
// Maximum response size. Sized for /api/status — which is the largest
// fixed-shape body we emit — with the Phase 0 wedge-attribution block
// (core1_iter, http_poll_fires, the close-cause buckets, MEMP pool
// stats, mbedtls slab stats) plus the spliced data_schema for up to
// CONDUIT_DATA_MAX_NAMES channels. 1 KB was silently truncating the
// body mid-string after the diag block landed.
#define HTTP_MAX_RESPONSE 2048

typedef enum {
    CONN_STATE_HEADER,     // Accumulating headers
    CONN_STATE_BODY,       // Receiving POST body
    CONN_STATE_DRAINING,   // OTA body fully received; waiting for Core 0 to flush
                           // ring and run the last flash write before responding
    CONN_STATE_WAITING,    // /api/log long-poll: holding until data or deadline
    CONN_STATE_STREAMING,  // /api/log?stream=1: persistent push of new bytes
    CONN_STATE_WS,         // /api/stream: bidirectional WebSocket. Frame codec
                           // and channel dispatch live in ws_server.{c,h}.
    CONN_STATE_DONE,       // Response sent, waiting for close
} conn_state_t;

typedef enum {
    METHOD_UNKNOWN = 0,
    METHOD_GET,
    METHOD_POST,
    METHOD_OPTIONS,
} http_method_t;

typedef enum {
    ROUTE_UNKNOWN = 0,
    ROUTE_STATUS,
    ROUTE_UPLOAD,
    ROUTE_REBOOT,
    ROUTE_COMMIT,
    ROUTE_LOG,
    ROUTE_DATA,         // /api/data — binary record stream
    ROUTE_DATA_SCHEMA,  // /api/data_schema — id→name JSON
    ROUTE_CMD,          // /api/cmd — POST command dispatch (auth)
    ROUTE_INCIDENTS,    // /api/incidents — GET list / POST clear (auth)
    ROUTE_STREAM,       // /api/stream — bidirectional WebSocket
} route_t;

typedef struct {
    conn_state_t state;
    http_method_t method;
    route_t route;
    bool authenticated;
    bool ota_start;    // X-OTA-Start: 1 — call ota_begin before streaming
    bool ota_finish;   // X-OTA-Finish: 1 — call ota_finish after body
    bool keep_alive;   // Send "Connection: keep-alive"; reset conn for the
                       // next request on the same TCP/TLS pcb instead of
                       // closing. Only ever set by the OTA intermediate-
                       // chunk path; closing is the safe default for
                       // every other endpoint.
    uint32_t content_length;
    uint32_t body_received;
    // OTA upload ack pacing — snapshot of ota_ring_total_drained() at the
    // last altcp_recved call for upload-body bytes. Each tick of http_poll
    // (and each recv cb) computes the delta and acks it, throttling the
    // peer's TCP window to Core 0's drain rate. See ota_pump_ack().
    uint32_t last_acked_drained;
    char header_buf[HTTP_MAX_HEADER];
    uint16_t header_len;
    bool headers_complete;
    // /api/log long-poll state (only meaningful when state == WAITING).
    uint32_t log_since;
    absolute_time_t log_deadline;
    // /api/data stream flag. STREAMING covers both /api/log?stream=1 and
    // /api/data?stream=1; this bit tells http_poll which ring to drain.
    bool data_stream;
    // Wall-clock of the last byte http_poll wrote to this PCB (real
    // record bytes OR a keepalive). When STREAMING ring is empty for
    // STREAM_KEEPALIVE_MS we emit a tiny in-band marker so the
    // browser's 1 s stall watchdog has something to count against —
    // without this, a quiet device looks identical to a wedged TX
    // path and the indicator flaps "no data" forever.
    absolute_time_t last_tx_at;
    // Wall-clock when the TCP/TLS accept fired for this conn. Used by
    // note_stream_close() to compute and stash the age of the most
    // recently closed streaming conn — a 22-min disconnect that lands
    // in stream_close_err_abrt looks very different from a 30-s one,
    // and the bucket alone doesn't carry that signal.
    absolute_time_t opened_at;
    // Per-conn WebSocket state. Only meaningful when state == CONN_STATE_WS;
    // ws_server_on_open() initializes it post-Upgrade. The conn's
    // header_buf (2 KB) doubles as the WS frame reassembly buffer
    // since we're done parsing HTTP requests by the time this is
    // active. See ws_server.h for the full per-conn state shape.
    ws_state_t ws;
} http_conn_t;

// --------------------------------------------------------------------------
// CORS / PNA headers appended to every response
// --------------------------------------------------------------------------
static const char *cors_headers =
    "Access-Control-Allow-Origin: " CONDUIT_CORS_ORIGIN "\r\n"
    "Access-Control-Allow-Methods: GET, POST, OPTIONS\r\n"
    "Access-Control-Allow-Headers: X-Auth-Token, Content-Type, "
        "X-OTA-Start, X-OTA-Finish\r\n"
    "Access-Control-Allow-Private-Network: true\r\n"
    "Access-Control-Max-Age: 86400\r\n";

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

static void get_board_id(char *out, size_t max) {
    pico_unique_board_id_t id;
    pico_get_unique_board_id(&id);
    size_t pos = 0;
    for (int i = 0; i < PICO_UNIQUE_BOARD_ID_SIZE_BYTES && pos + 2 < max; i++) {
        pos += snprintf(out + pos, max - pos, "%02x", id.id[i]);
    }
}

// Case-insensitive header search. Returns pointer to value (after ": ") or NULL.
static const char *find_header(const char *headers, const char *name) {
    size_t name_len = strlen(name);
    const char *p = headers;
    while (*p) {
        // Compare header name case-insensitively
        if (strncasecmp(p, name, name_len) == 0 && p[name_len] == ':') {
            const char *val = p + name_len + 1;
            while (*val == ' ') val++;
            return val;
        }
        // Skip to next line
        const char *nl = strstr(p, "\r\n");
        if (!nl) break;
        p = nl + 2;
    }
    return NULL;
}

// Get value of a header as a string, up to delimiter (usually \r\n)
static size_t copy_header_value(const char *val, char *out, size_t max) {
    size_t i = 0;
    while (val[i] && val[i] != '\r' && val[i] != '\n' && i < max - 1) {
        out[i] = val[i];
        i++;
    }
    out[i] = '\0';
    return i;
}

// Forward decls.
static err_t http_poll(void *arg, struct altcp_pcb *pcb);
static void conn_close(struct altcp_pcb *pcb, http_conn_t *conn);
static void enable_keepalive(struct altcp_pcb *pcb);

// --------------------------------------------------------------------------
// Streaming-connection registry
// --------------------------------------------------------------------------
// Tracks currently-open /api/log?stream=1 and /api/data?stream=1 PCBs
// so http_server_on_link_down() can abort them all on cable unplug.
// Without this, vanished-client streamers sit in the small
// MEMP_NUM_TCP_PCB pool for ~50 s (keepalive probe duration) and the
// browser's reconnect SYNs get refused because the pool is full.
typedef struct {
    struct altcp_pcb *pcb;
    http_conn_t    *conn;
} stream_reg_entry_t;

#define STREAM_REG_SIZE  MEMP_NUM_TCP_PCB
static stream_reg_entry_t stream_registry[STREAM_REG_SIZE];

// ---- http_conn_t static pool ----------------------------------------------
//
// Each accepted connection used to allocate sizeof(http_conn_t) (~2 KB)
// via libc calloc, putting load on the newlib heap. Under stream-reconnect
// churn (every TLS retry is a fresh accept) the heap fragmented and
// eventually a single calloc returned NULL — pico_malloc's PICO_MALLOC_PANIC
// kicked in, panic()'d Core 1, and the firmware froze until the Core 1
// watchdog rebooted it. Fix: a fixed-size static pool. One slot per
// MEMP_NUM_TCP_PCB; same peak usage as the malloc path but no
// fragmentation, no allocation failure, no panic.
// 5 covered the bare-minimum IDE session (2 streams + 1 OTA + 1
// control + 1 handshake-overlap) but was being saturated in practice:
// a second browser tab, an HTTPS status fetch racing with the IDE WS,
// or a stuck post-link-down conn that lingered for ~50 s would push
// us past 5 and start RSTing new SYNs. 7 leaves two slots of headroom
// for those transient overlaps. Each slot ~2 KB → +4 KB BSS, comfortably
// within MEM_SIZE=128 KB budget. Pool exhaustion still surfaces as
// ERR_MEM on the new accept (RST'd SYN, peer retries cleanly).
#define HTTP_CONN_POOL_SIZE  7
static http_conn_t http_conn_pool[HTTP_CONN_POOL_SIZE];
static bool        http_conn_in_use[HTTP_CONN_POOL_SIZE];

static http_conn_t *http_conn_alloc(void) {
    for (int i = 0; i < HTTP_CONN_POOL_SIZE; i++) {
        if (!http_conn_in_use[i]) {
            http_conn_in_use[i] = true;
            memset(&http_conn_pool[i], 0, sizeof http_conn_pool[i]);
            return &http_conn_pool[i];
        }
    }
    return NULL;
}

static void http_conn_free(http_conn_t *conn) {
    if (!conn) return;
    ptrdiff_t i = conn - http_conn_pool;
    if (i >= 0 && i < HTTP_CONN_POOL_SIZE) {
        http_conn_in_use[i] = false;
    }
}

// HTTP-server-specific diagnostic counters surfaced via diag.c. See the
// header for what each tracks and how to interpret deltas across a
// cable cycle.
static volatile uint32_t g_accepts_total         = 0;
static volatile uint32_t g_streams_started_total = 0;
// http_poll is the per-conn poll callback driven by lwIP's tcp_tmr.
// If this counter stops advancing while core1_iter is still climbing,
// it pins lwIP's slow-timer subsystem as the wedged piece (e.g. the
// tcp_tmr() reschedule failed because MEMP_NUM_SYS_TIMEOUT was
// exhausted). Visible in /api/status alongside accepts_total and
// the close-cause counters so a post-wedge HTTPS fetch can attribute.
static volatile uint32_t g_http_poll_fires       = 0;

uint32_t http_server_accepts(void)         { return g_accepts_total; }
uint32_t http_server_streams_started(void) { return g_streams_started_total; }
uint32_t http_server_poll_fires(void)      { return g_http_poll_fires; }

// Why a streaming connection (CONN_STATE_STREAMING / CONN_STATE_WS) ended.
// The browser-side WS sees every one of these as the same 1006 "abnormal
// close — no close frame". Without device-side attribution, "session lasted
// 22 min, then died" is unbucketable: was it our retransmits exhausting
// (ERR_ABRT from lwIP), the peer RSTing (ERR_RST), a TLS internal abort
// (also ERR_ABRT — distinguishable only by other signals like stale TX),
// a WS protocol error we hit, etc. Each path bumps exactly one bucket so
// /api/status post-incident shows the cause.
typedef enum {
    STREAM_CLOSE_RECV_EOF      = 0,  // http_recv got NULL pbuf (clean peer FIN)
    STREAM_CLOSE_RECV_ERR      = 1,  // http_recv called with err != ERR_OK
    STREAM_CLOSE_ERR_RST       = 2,  // lwIP err_cb: ERR_RST  (peer RST or local RST)
    STREAM_CLOSE_ERR_ABRT      = 3,  // lwIP err_cb: ERR_ABRT (RTO exhausted OR mbedtls internal abort)
    STREAM_CLOSE_ERR_CLSD      = 4,  // lwIP err_cb: ERR_CLSD
    STREAM_CLOSE_ERR_OTHER     = 5,  // lwIP err_cb: any other code
    STREAM_CLOSE_WRITE_ERR     = 6,  // altcp_write returned non-MEM error
    STREAM_CLOSE_WS_PARSE_FAIL = 7,  // ws_server_on_bytes returned false
    STREAM_CLOSE_LINK_DOWN     = 8,  // http_server_on_link_down() swept
    STREAM_CLOSE_COUNT         = 9,
} stream_close_reason_t;

static volatile uint32_t g_stream_closes[STREAM_CLOSE_COUNT];
static volatile int32_t  g_stream_last_close_err    = 0;  // lwIP err code from the most recent err_cb
static volatile uint32_t g_stream_last_close_age_ms = 0;  // wall-clock lifetime of the most recently closed streaming conn

// Bump the close-cause counter for a streaming conn, plus stash the age
// of the most recently closed streaming conn so a "22 min vs 30 s"
// signal is visible without per-event logging. Safe to call with conn
// == NULL (skips age update). Only counts conns in STREAMING / WS state
// — short-lived requests (status/cmd/upload-finalize) close on a normal
// path and aren't a reconnect-loss signal.
static void note_stream_close(stream_close_reason_t reason, http_conn_t *conn) {
    if (!conn) return;
    if (conn->state != CONN_STATE_STREAMING && conn->state != CONN_STATE_WS) return;
    if (reason >= STREAM_CLOSE_COUNT) return;
    g_stream_closes[reason]++;
    g_stream_last_close_age_ms =
        (uint32_t)(absolute_time_diff_us(conn->opened_at, get_absolute_time()) / 1000);
}

static void register_streaming(struct altcp_pcb *pcb, http_conn_t *conn) {
    for (int i = 0; i < STREAM_REG_SIZE; i++) {
        if (stream_registry[i].pcb == NULL) {
            stream_registry[i].pcb  = pcb;
            stream_registry[i].conn = conn;
            return;
        }
    }
}

// Snapshot of how many streaming-state conns are live right now —
// surfaced in /api/status so a 22-min disconnect can be cross-checked
// against "did we still have N concurrent streams when this one died,
// or did they all die together (link/wifi-side cause)".
static int count_streaming_conns(void) {
    int n = 0;
    for (int i = 0; i < STREAM_REG_SIZE; i++) {
        if (stream_registry[i].pcb != NULL) n++;
    }
    return n;
}

// Idempotent. Matches by pcb when available, otherwise by conn (http_err
// only has the conn pointer because lwIP has already freed the pcb by
// the time the err callback fires).
static void unregister_streaming(struct altcp_pcb *pcb, http_conn_t *conn) {
    for (int i = 0; i < STREAM_REG_SIZE; i++) {
        if ((pcb && stream_registry[i].pcb == pcb) ||
            (conn && stream_registry[i].conn == conn)) {
            stream_registry[i].pcb  = NULL;
            stream_registry[i].conn = NULL;
            return;
        }
    }
}

// --------------------------------------------------------------------------
// Response builders
// --------------------------------------------------------------------------

// Send a response with `Connection: close`. Default for every endpoint
// except the OTA intermediate-chunk path (see send_response_keepalive).
static err_t send_response(struct altcp_pcb *pcb, const char *status,
                           const char *content_type, const char *body, size_t body_len) {
    char hdr[512];
    int hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.1 %s\r\n"
        "Content-Type: %s\r\n"
        "Content-Length: %u\r\n"
        "Connection: close\r\n"
        "%s"
        "\r\n",
        status, content_type, (unsigned)body_len, cors_headers);

    altcp_write(pcb, hdr, hdr_len, TCP_WRITE_FLAG_COPY);
    if (body && body_len > 0) {
        altcp_write(pcb, body, body_len, TCP_WRITE_FLAG_COPY);
    }
    altcp_output(pcb);
    return ERR_OK;
}

// Same as send_response, but advertises Connection: keep-alive so the
// client can reuse this TCP/TLS connection for the next request. Used
// for OTA intermediate chunks where 47 sequential POSTs would otherwise
// each pay a fresh TLS handshake (~1 s) and burn a PCB; with keep-alive
// the whole upload runs over one connection.
static err_t send_response_keepalive(struct altcp_pcb *pcb, const char *status,
                                     const char *content_type,
                                     const char *body, size_t body_len) {
    char hdr[512];
    int hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.1 %s\r\n"
        "Content-Type: %s\r\n"
        "Content-Length: %u\r\n"
        "Connection: keep-alive\r\n"
        "%s"
        "\r\n",
        status, content_type, (unsigned)body_len, cors_headers);

    altcp_write(pcb, hdr, hdr_len, TCP_WRITE_FLAG_COPY);
    if (body && body_len > 0) {
        altcp_write(pcb, body, body_len, TCP_WRITE_FLAG_COPY);
    }
    altcp_output(pcb);
    return ERR_OK;
}

static err_t send_json(struct altcp_pcb *pcb, const char *status, const char *json) {
    return send_response(pcb, status, "application/json", json, strlen(json));
}

static err_t send_error(struct altcp_pcb *pcb, const char *status, const char *message) {
    char buf[256];
    int len = snprintf(buf, sizeof(buf), "{\"error\":\"%s\"}", message);
    return send_response(pcb, status, "application/json", buf, len);
}

static err_t send_cors_preflight(struct altcp_pcb *pcb) {
    return send_response(pcb, "204 No Content", "text/plain", NULL, 0);
}

// --------------------------------------------------------------------------
// Route handlers
// --------------------------------------------------------------------------

// Build the device-status JSON into `out`. Shared between the HTTP
// /api/status path and the WS_CH_STATUS push from ws_server.c, so a
// schema change touches one place.
int http_server_build_status_json(char *out, size_t out_max) {
    if (!out || out_max == 0) return 0;
    char board_id[32];
    get_board_id(board_id, sizeof(board_id));

    // Detect which A/B partition we booted from.
    // rom_get_boot_info returns >= 0 on success.
    char active_partition = '?';
    boot_info_t boot_info;
    if (rom_get_boot_info(&boot_info) >= 0) {
        switch (boot_info.partition) {
            case 0:  active_partition = 'A'; break;
            case 1:  active_partition = 'B'; break;
            case -1: active_partition = '-'; break; // unpartitioned / direct boot
            default: active_partition = '?'; break;
        }
    }

    // Snapshot Phase 0 diag fields up-front (cheap reads from BSS) so
    // the long snprintf below has a flat list of values to plug in.
    // Keeping the gather here rather than inlining avoids re-walking
    // the TCP-PCB lists three times across the format string.
    struct {
        uint32_t core1_iter;
        unsigned pbuf_used, pbuf_max;
        unsigned tcp_pcb_used, tcp_pcb_max;
        unsigned sys_timeout_used, sys_timeout_max;
        unsigned tcp_pcbs_active, tcp_pcbs_tw, tcp_pcbs_listen;
        uint32_t ip_drops, tcp_drops, tcp_errs, tcp_chkerrs;
        unsigned mbedtls_exhausted_in, mbedtls_exhausted_out;
    } diag_status = {0};

    diag_status.core1_iter = __atomic_load_n(&g_core1_iter, __ATOMIC_RELAXED);

    // lwIP MEMP_STATS — pinned ON in lwipopts.h:163 already. .memp[]
    // entries are pointers, dereferenced for used + max. The pools we
    // care about for wedge attribution:
    //   PBUF_POOL      — leaked pbufs are the most common wedge cause
    //   TCP_PCB        — listener fails to accept if this hits max
    //   SYS_TIMEOUT    — tcp_tmr can't reschedule itself when full
    const struct stats_mem *pbm = lwip_stats.memp[MEMP_PBUF_POOL];
    if (pbm) { diag_status.pbuf_used = pbm->used; diag_status.pbuf_max = pbm->max; }
    const struct stats_mem *tpm = lwip_stats.memp[MEMP_TCP_PCB];
    if (tpm) { diag_status.tcp_pcb_used = tpm->used; diag_status.tcp_pcb_max = tpm->max; }
    const struct stats_mem *stm = lwip_stats.memp[MEMP_SYS_TIMEOUT];
    if (stm) { diag_status.sys_timeout_used = stm->used; diag_status.sys_timeout_max = stm->max; }

    conduit_diag_count_tcp_pcbs(&diag_status.tcp_pcbs_active,
                                &diag_status.tcp_pcbs_tw,
                                &diag_status.tcp_pcbs_listen);

    diag_status.ip_drops    = lwip_stats.ip.drop;
    diag_status.tcp_drops   = lwip_stats.tcp.drop;
    diag_status.tcp_errs    = lwip_stats.tcp.err;
    diag_status.tcp_chkerrs = lwip_stats.tcp.chkerr;

    conduit_mbedtls_slab_stats_t slab;
    conduit_mbedtls_slab_stats(&slab);
    diag_status.mbedtls_exhausted_in  = slab.exhausted_in;
    diag_status.mbedtls_exhausted_out = slab.exhausted_out;

    // Build the body without the trailing `}` so we can splice in
    // the inlined data_schema below. The /api/data_schema endpoint
    // stays live for backwards compat, but the IDE no longer needs
    // a separate HTTPS round-trip to learn the channel registry —
    // it reads the schema straight off the STATUS frame the device
    // pushes immediately after auth. That cuts one full TLS
    // handshake off the cold-page-load critical path on wss (a
    // fresh fetch() to the wildcard hostname doesn't share TLS
    // session state with the existing wss WebSocket pool in Chrome,
    // so the second handshake costs another ~2 s on Cortex-M33).
    int len = snprintf(out, out_max,
        "{"
        "\"version\":\"%s\","
        // binary_version is the picobin MAJOR.MINOR baked in by
        // pico_set_binary_version — what the RP2350 bootrom actually
        // compares for A/B selection. Use this (NOT `version` above,
        // which is a fixed semver from CONDUIT_VERSION_STRING) when
        // verifying that a TBYB rollback flipped to the previous image.
        "\"binary_version\":\"%d.%d\","
        "\"ip\":\"%s\","
        "\"mac\":\"%s\","
        "\"uptime\":%u,"
        "\"link\":%s,"
        "\"poe\":%s,"
        "\"partition\":\"%c\","
        "\"board_id\":\"%s\","
        "\"ota_in_progress\":%s,"
        "\"ota_bytes_written\":%u,"
        "\"rx_drops\":%u,"
        "\"boot_type\":\"%s\","
        "\"tbyb_pending\":%s,"
        // Data-ring eviction telemetry — see data_buffer.c for the
        // mechanism. Non-zero values here mean the producer has at
        // some point written faster than the consumer drained, and
        // we silently overwrote ring contents. The corresponding
        // browser-side symptom is gaps in uptime_us. Use this to
        // cross-check HDF5 exports: if data_ring_evictions matches
        // the analyzer's gap_count, the gaps are consumer-stall
        // driven; if zero and gaps exist, the device emit loop
        // itself paused.
        "\"data_ring_evictions\":%u,"
        "\"data_ring_evicted_bytes\":%u,"
        // Streaming-conn close-cause attribution. Bumps live in
        // note_stream_close(); see stream_close_reason_t for what each
        // bucket means. All of these manifest as the same 1006
        // "abnormal close, no close frame" in the browser — only the
        // device knows which path actually fired. `last_close_err` is
        // the lwIP err code (or write err) from whichever close most
        // recently incremented one of these, and `last_close_age_ms`
        // is how long that conn was alive — a 22-min lifetime in
        // err_abrt looks very different from a 30-s one.
        "\"streams_open\":%d,"
        "\"stream_close_recv_eof\":%u,"
        "\"stream_close_recv_err\":%u,"
        "\"stream_close_err_rst\":%u,"
        "\"stream_close_err_abrt\":%u,"
        "\"stream_close_err_clsd\":%u,"
        "\"stream_close_err_other\":%u,"
        "\"stream_close_write_err\":%u,"
        "\"stream_close_ws_parse_fail\":%u,"
        "\"stream_close_link_down\":%u,"
        "\"stream_last_close_err\":%d,"
        "\"stream_last_close_age_ms\":%u,"
        // Phase 0 wedge-attribution counters. Last incident: device
        // ICMP-pingable, both TCP listeners refused SYN, USB CDC silent,
        // LED blinking at unchanged 1 kHz cadence (so Core 0 healthy).
        // Out-of-band /api/status fetch via HTTPS was the only way to
        // see device state; these counters tell us which subsystem
        // wedged so the next recurrence is attributable instead of
        // guessable.
        //   core1_iter      — bumped per Core 1 RMII poll iteration
        //                     (after sys_check_timeouts). Stalled =
        //                     poll loop wedged; Core 0's 3 s detector
        //                     would have rebooted us already.
        //   http_poll_fires — bumped on entry to the per-conn poll cb
        //                     (driven by lwIP tcp_tmr/slow timer).
        //                     Flat while core1_iter climbs = slow
        //                     timer wedge (e.g. sys_timeout pool full
        //                     so tcp_tmr can't reschedule itself).
        //   http_accepts    — increments per http_accept call. Flat
        //                     under inbound SYNs = SYNs not reaching
        //                     the listen pcb (tcp_listen_input path
        //                     broken or listen pcb gone).
        //   pbuf_used/max, sys_timeout_used/max, tcp_pcb_used/max —
        //     lwIP MEMP_STATS. `_used` at `_max` is direct pool
        //     exhaustion; chain through what allocates each.
        //   tcp_pcbs_active/timewait/listen — live PCB list census.
        //   ip_drops, tcp_drops/errs/chkerrs — lwIP drop counters.
        //     Climbing while http_accepts stays flat localizes the
        //     packet rejection point.
        //   mbedtls_slab_exhausted_{in,out} — TLS session-buffer
        //     exhaustion (3-slot static slab); explains a wedge if
        //     handshakes pile up and the slab leaks.
        "\"core1_iter\":%u,"
        "\"http_poll_fires\":%u,"
        "\"http_accepts\":%u,"
        "\"http_streams_started\":%u,"
        "\"pbuf_used\":%u,\"pbuf_max\":%u,"
        "\"tcp_pcb_used\":%u,\"tcp_pcb_max\":%u,"
        "\"sys_timeout_used\":%u,\"sys_timeout_max\":%u,"
        "\"tcp_pcbs_active\":%u,\"tcp_pcbs_timewait\":%u,\"tcp_pcbs_listen\":%u,"
        "\"ip_drops\":%u,\"tcp_drops\":%u,\"tcp_errs\":%u,\"tcp_chkerrs\":%u,"
        "\"mbedtls_slab_exhausted_in\":%u,\"mbedtls_slab_exhausted_out\":%u,"
        "\"device\":\"conduit\""
        ,
        CONDUIT_VERSION_STRING,
        CONDUIT_BINARY_VERSION_MAJOR, CONDUIT_BINARY_VERSION_MINOR,
        network_get_ip_str(),
        network_get_mac_str(),
        network_get_uptime_s(),
        network_is_link_up() ? "true" : "false",
        network_get_poe_status() ? "true" : "false",
        active_partition,
        board_id,
        ota_in_progress() ? "true" : "false",
        ota_bytes_written(),
        (unsigned)netif_rmii_ethernet_rx_drops(),
        ota_boot_type_str(),
        ota_commit_pending() ? "true" : "false",
        data_buffer_evictions_total(),
        data_buffer_evicted_bytes_total(),
        count_streaming_conns(),
        g_stream_closes[STREAM_CLOSE_RECV_EOF],
        g_stream_closes[STREAM_CLOSE_RECV_ERR],
        g_stream_closes[STREAM_CLOSE_ERR_RST],
        g_stream_closes[STREAM_CLOSE_ERR_ABRT],
        g_stream_closes[STREAM_CLOSE_ERR_CLSD],
        g_stream_closes[STREAM_CLOSE_ERR_OTHER],
        g_stream_closes[STREAM_CLOSE_WRITE_ERR],
        g_stream_closes[STREAM_CLOSE_WS_PARSE_FAIL],
        g_stream_closes[STREAM_CLOSE_LINK_DOWN],
        (int)g_stream_last_close_err,
        g_stream_last_close_age_ms,
        diag_status.core1_iter,
        g_http_poll_fires,
        g_accepts_total,
        g_streams_started_total,
        diag_status.pbuf_used, diag_status.pbuf_max,
        diag_status.tcp_pcb_used, diag_status.tcp_pcb_max,
        diag_status.sys_timeout_used, diag_status.sys_timeout_max,
        diag_status.tcp_pcbs_active, diag_status.tcp_pcbs_tw, diag_status.tcp_pcbs_listen,
        diag_status.ip_drops, diag_status.tcp_drops, diag_status.tcp_errs, diag_status.tcp_chkerrs,
        diag_status.mbedtls_exhausted_in, diag_status.mbedtls_exhausted_out);
    if (len < 0) return 0;
    if ((size_t)len >= out_max) return (int)(out_max - 1);

    // Splice `,"data_schema":<schema>}` into the remaining buffer.
    // data_buffer_schema_json builds a `{...}` object directly into
    // the supplied buffer so we hand it the slot AFTER our own
    // `,"data_schema":` prefix. On overflow we just close the JSON
    // without the schema field — IDE falls back to /api/data_schema.
    const size_t remaining_before_schema = out_max - (size_t)len;
    const char *schema_prefix = ",\"data_schema\":";
    const size_t prefix_len = strlen(schema_prefix);
    if (remaining_before_schema > prefix_len + 2) {  // need at least ',"data_schema":{}}\0' worth
        memcpy(out + len, schema_prefix, prefix_len);
        size_t schema_len = data_buffer_schema_json(out + len + prefix_len,
                                                    remaining_before_schema - prefix_len - 2);
        if (schema_len > 0) {
            len += (int)(prefix_len + schema_len);
        }
    }
    // Close the JSON object.
    if ((size_t)len < out_max - 1) {
        out[len++] = '}';
        out[len] = '\0';
    } else {
        out[out_max - 1] = '\0';
        len = (int)(out_max - 1);
    }
    return len;
}

static void handle_status(struct altcp_pcb *pcb) {
    char json[HTTP_MAX_RESPONSE];
    int n = http_server_build_status_json(json, sizeof(json));
    if (n <= 0) {
        send_error(pcb, "500 Internal Server Error", "status build failed");
        return;
    }
    send_response(pcb, "200 OK", "application/json", json, (size_t)n);
}

// GET /api/incidents — JSON array of records persisted across reboots
// (Core 1 wedges, hardware watchdog resets, OTA rollbacks, manual test
// inserts). Read-only; the POST variant clears them.
static void handle_incidents_get(struct altcp_pcb *pcb) {
    static char buf[3072];
    int off = 0;
    off += snprintf(buf + off, sizeof buf - off, "[");
    unsigned n = incident_log_count();
    for (unsigned i = 0; i < n && off < (int)sizeof buf - 256; i++) {
        const incident_record_t *r = incident_log_get(i);
        if (!r) break;
        // Cause name kept terse; the web renderer can map further.
        const char *cause;
        switch (r->cause) {
            case INCIDENT_BOOT:              cause = "boot";         break;
            case INCIDENT_CORE1_WEDGE:       cause = "core1-wedge";  break;
            case INCIDENT_HW_WATCHDOG_RESET: cause = "hw-watchdog";  break;
            case INCIDENT_OTA_ROLLBACK:      cause = "ota-rollback"; break;
            case INCIDENT_MANUAL:            cause = "manual";       break;
            default:                         cause = "?";            break;
        }
        // Defensive escape: msg can contain " or \ if a future caller
        // forwards an arbitrary string. Replace those with '?'. We
        // don't bother with proper JSON escaping for a forensic field.
        char safe_msg[sizeof r->msg];
        size_t mlen = strnlen(r->msg, sizeof r->msg);
        for (size_t k = 0; k < mlen; k++) {
            char c = r->msg[k];
            safe_msg[k] = (c == '"' || c == '\\' || c < 0x20) ? '?' : c;
        }
        safe_msg[mlen] = '\0';
        off += snprintf(buf + off, sizeof buf - off,
            "%s{\"i\":%u,\"cause\":\"%s\",\"uptime_ms\":%u,"
            "\"c1\":%u,\"heap_used\":%u,\"pcb_active\":%u,"
            "\"binary_version\":\"%u.%u\",\"msg\":\"%s\"}",
            i == 0 ? "" : ",",
            i, cause,
            (unsigned)r->uptime_ms,
            (unsigned)r->c1_value,
            (unsigned)r->heap_used,
            (unsigned)r->pcb_active,
            (unsigned)(r->binary_version >> 16),
            (unsigned)(r->binary_version & 0xFFFFu),
            safe_msg);
    }
    snprintf(buf + off, sizeof buf - off, "]");
    send_json(pcb, "200 OK", buf);
}

// POST /api/incidents
//   ?action=clear → erase the log sector (auth required)
//   ?action=test  → append an INCIDENT_MANUAL record (auth required) —
//                   useful for verifying the flash path end-to-end
//                   without having to actually wedge the device.
static void handle_incidents_post(struct altcp_pcb *pcb, http_conn_t *conn) {
    if (!conn->authenticated) {
        send_error(pcb, "403 Forbidden", "invalid or missing auth token");
        return;
    }
    const char *q = strchr(conn->header_buf, '?');
    bool clear = false, test = false;
    if (q) {
        if (strstr(q, "action=clear")) clear = true;
        else if (strstr(q, "action=test")) test = true;
    }
    if (clear) {
        if (incident_log_clear() == 0) {
            send_json(pcb, "200 OK", "{\"ok\":true,\"action\":\"clear\"}");
        } else {
            send_error(pcb, "500 Internal Server Error", "flash clear failed");
        }
        return;
    }
    if (test) {
        if (incident_log_append(INCIDENT_MANUAL, "manual test entry") == 0) {
            send_json(pcb, "200 OK", "{\"ok\":true,\"action\":\"test\"}");
        } else {
            send_error(pcb, "500 Internal Server Error", "flash append failed");
        }
        return;
    }
    send_error(pcb, "400 Bad Request", "specify ?action=clear or ?action=test");
}

static void handle_upload_begin(struct altcp_pcb *pcb, http_conn_t *conn) {
    if (!conn->authenticated) {
        send_error(pcb, "403 Forbidden", "invalid or missing auth token");
        conn->state = CONN_STATE_DONE;
        return;
    }

    // Three valid request shapes:
    //   X-OTA-Start   → begin a new session, then stream body bytes.
    //   X-OTA-Finish  → stream body bytes into an already-open session,
    //                   and call ota_finish() at end-of-body.
    //   (neither)     → stream body bytes into an already-open session,
    //                   keep it open.
    // Legacy one-shot uploads should set BOTH X-OTA-Start and X-OTA-Finish.
    if (conn->ota_start) {
        ota_err_t err = ota_begin();
        if (err != OTA_OK) {
            send_error(pcb, "500 Internal Server Error", ota_error_string(err));
            conn->state = CONN_STATE_DONE;
            return;
        }
    } else if (!ota_in_progress()) {
        send_error(pcb, "409 Conflict", "no OTA session in progress");
        conn->state = CONN_STATE_DONE;
        return;
    }

    conn->state = CONN_STATE_BODY;
    // Snapshot the ring's drain counter so ota_pump_ack only credits
    // bytes Core 0 drains AFTER this upload started.
    conn->last_acked_drained = ota_ring_total_drained();
    // Register periodic poll. lwIP's TCP slow timer fires every ~500 ms;
    // with peer's window closed (we defer all upload-body acks), normal
    // recv callbacks stop firing — http_poll is what wakes us up to
    // credit drained bytes back into the window.
    altcp_poll(pcb, http_poll, 1);
    DEV_LOG("[ota] upload begin: state→BODY, content_length=%u, poll registered\n",
            (unsigned)conn->content_length);
}

// Credit any bytes Core 0 has drained since the last call back into the
// TCP receive window. Called from both http_recv (catch-up on each new
// pbuf) and http_poll (drives forward progress while peer's window is
// closed). Safe to call any time on the upload conn — caps to u16_t
// chunks if Core 0 got way ahead between calls.
//
// altcp_output() is called AFTER altcp_recved so the window-update
// packet is flushed onto the wire NOW instead of waiting for lwIP's
// silly-window threshold to be met by accumulating credits. Without
// this, small per-poll credits (e.g. 1.5–3 KB per 100 ms) can sit
// in pcb->rcv_wnd unannounced for seconds while the peer is stuck
// in zero-window persist.
static void ota_pump_ack(struct altcp_pcb *pcb, http_conn_t *conn) {
    uint32_t drained_now = ota_ring_total_drained();
    uint32_t newly = drained_now - conn->last_acked_drained;
    if (newly == 0) return;
    while (newly > 0) {
        u16_t chunk = (newly > 0xFFFF) ? 0xFFFF : (u16_t)newly;
        altcp_recved(pcb, chunk);
        newly -= chunk;
        conn->last_acked_drained += chunk;
    }
    // Force the window update onto the wire immediately. Without this,
    // lwIP's silly-window-avoidance can sit on small credits until they
    // accumulate past TCP_WND_UPDATE_THRESHOLD — which never happens
    // for a stalled peer in zero-window persist.
    altcp_output(pcb);
}

// Producer side. Always expects to fully accept `len` into the ring
// because TCP_WND < OTA_RING_SIZE and the peer's window is held closed
// (via deferred altcp_recved) until Core 0 drains. If the ring DOES
// overflow somehow, we've lost bytes (lwIP already TCP-acked them) and
// must abort — the in-flight image would be corrupt.
static size_t handle_upload_data(struct altcp_pcb *pcb, http_conn_t *conn,
                                 const uint8_t *data, size_t len) {
    size_t accepted = ota_write_chunk_ex(data, len);
    if (accepted < len) {
        DEV_LOG("[ota] ring overflow: accepted=%u/%u — TCP_WND vs ring sizing bug\n",
                (unsigned)accepted, (unsigned)len);
        send_error(pcb, "500 Internal Server Error", "ring overflow");
        ota_abort();
        conn->state = CONN_STATE_DONE;
        return accepted;
    }
    conn->body_received += accepted;

    if (conn->content_length > 0 && conn->body_received >= conn->content_length) {
        if (conn->ota_finish) {
            // All body bytes are in the ring (or already flashed). Hand
            // off to the Core-0 pump to drain and finalize. http_poll
            // (registered at handle_upload_begin) wakes on each TCP slow
            // tick to check ota_drain_complete and send the response.
            conn->state = CONN_STATE_DRAINING;
            ota_begin_drain();
        } else {
            // Intermediate chunk — ack with current progress, keep OTA open.
            // Advertise Connection: keep-alive so the client reuses this
            // TCP/TLS pcb for the next chunk. http_recv resets the conn
            // for the next request based on conn->keep_alive.
            char body[96];
            int n = snprintf(body, sizeof(body),
                "{\"ok\":true,\"bytes_written\":%u}", (unsigned)ota_bytes_written());
            conn->keep_alive = true;
            send_response_keepalive(pcb, "200 OK", "application/json", body, (size_t)n);
            conn->state = CONN_STATE_DONE;
        }
    }
    return accepted;
}

static void handle_reboot(struct altcp_pcb *pcb, http_conn_t *conn) {
    if (!conn->authenticated) {
        send_error(pcb, "403 Forbidden", "invalid or missing auth token");
        conn->state = CONN_STATE_DONE;
        return;
    }

    send_json(pcb, "200 OK", "{\"ok\":true,\"message\":\"rebooting\"}");
    conn->state = CONN_STATE_DONE;

    // Reboot after a short delay to let the response send.
    //
    // g_reboot_pending tells main() (on core 0) to stop calling
    // watchdog_update() — rom_reboot / watchdog_reboot program the same
    // watchdog LOAD register to fire the reset after delay_ms, and if the
    // main loop pats the dog during that window the countdown is reset
    // before it can fire. See memory:project_rom_reboot_watchdog_race.
    sleep_ms(200);
    extern volatile bool g_reboot_pending;
    __atomic_store_n(&g_reboot_pending, true, __ATOMIC_RELEASE);
    watchdog_reboot(0, 0, 100);
    // Busy-wait while the watchdog counts down.
    while (1) tight_loop_contents();
}

// Send the log response for a given `since`. Used by both the immediate
// path and the long-poll deadline path. log_out is static because both
// callers run on the lwIP tcpip thread, so calls are serialized.
static void send_log_response(struct altcp_pcb *pcb, uint32_t since) {
    static uint8_t log_out[4096];
    uint32_t next_cursor = since;
    size_t n = log_buffer_read(since, log_out, sizeof(log_out), &next_cursor);

    char hdr[768];
    int hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/plain; charset=utf-8\r\n"
        "Content-Length: %u\r\n"
        "X-Log-Cursor: %u\r\n"
        "Cache-Control: no-store\r\n"
        "Connection: close\r\n"
        "%s"
        "Access-Control-Expose-Headers: X-Log-Cursor\r\n"
        "\r\n",
        (unsigned)n, (unsigned)next_cursor, cors_headers);
    // snprintf returns the length it WOULD have written if the buffer were
    // unbounded; clamp so we never tcp_write bytes past the buffer end.
    if (hdr_len < 0) hdr_len = 0;
    if (hdr_len > (int)sizeof(hdr)) hdr_len = (int)sizeof(hdr);
    altcp_write(pcb, hdr, hdr_len, TCP_WRITE_FLAG_COPY);
    if (n > 0) altcp_write(pcb, log_out, n, TCP_WRITE_FLAG_COPY);
    altcp_output(pcb);
}

// Send the streaming-mode response headers — no Content-Length, no
// Transfer-Encoding; the body extends until we close the connection.
// HTTP/1.1 § 3.3.3 case 7 allows this when Connection: close is set, and
// browsers consume it via fetch().body.getReader() with no special framing.
static void send_log_stream_headers(struct altcp_pcb *pcb, uint32_t start_cursor) {
    char hdr[768];
    int hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/plain; charset=utf-8\r\n"
        "X-Log-Cursor: %u\r\n"
        "Cache-Control: no-store\r\n"
        // Disables proxy buffering on nginx/caddy paths (harmless otherwise);
        // ensures intermediaries flush each tcp_write through immediately.
        "X-Accel-Buffering: no\r\n"
        "Connection: close\r\n"
        "%s"
        "Access-Control-Expose-Headers: X-Log-Cursor\r\n"
        "\r\n",
        (unsigned)start_cursor, cors_headers);
    if (hdr_len < 0) hdr_len = 0;
    if (hdr_len > (int)sizeof(hdr)) hdr_len = (int)sizeof(hdr);
    altcp_write(pcb, hdr, hdr_len, TCP_WRITE_FLAG_COPY);
    altcp_output(pcb);
}

// Return the chunk of the log ring buffer the caller hasn't seen yet.
// GET /api/log                       → empty body, X-Log-Cursor: <current>.
// GET /api/log?since=N               → bytes [N, next_cursor) immediately.
// GET /api/log?since=N&wait_ms=M     → long-poll: hold up to M ms (≤30_000),
//                                      respond on first byte OR deadline.
// GET /api/log?since=N&stream=1      → persistent stream: connection stays
//                                      open and the firmware writes new
//                                      bytes as conduit_log() produces them,
//                                      until the client closes. Client
//                                      tracks cursor by counting received
//                                      bytes (initial position is the
//                                      X-Log-Cursor header on the response).
// Client updates its cursor from X-Log-Cursor. If the client fell behind
// more than LOG_BUFFER_SIZE bytes the firmware fast-forwards to the oldest
// retained byte.
//
// No auth required — this endpoint is read-only and only exposes printf
// output, which is already echoed on USB serial.
static void handle_log(struct altcp_pcb *pcb, http_conn_t *conn) {
    // Parse ?since=N, ?wait_ms=M, ?stream=1 from the request line.
    uint32_t since = 0;
    uint32_t wait_ms = 0;
    bool have_since = false;
    bool stream = false;
    {
        const char *space = strchr(conn->header_buf, ' ');
        const char *q = space ? strchr(space + 1, '?') : NULL;
        const char *end = space ? strchr(space + 1, ' ') : NULL;
        if (q && end && q < end) {
            const char *p = q + 1;
            while (p < end) {
                if (strncmp(p, "since=", 6) == 0) {
                    since = (uint32_t)strtoul(p + 6, NULL, 10);
                    have_since = true;
                } else if (strncmp(p, "wait_ms=", 8) == 0) {
                    wait_ms = (uint32_t)strtoul(p + 8, NULL, 10);
                    // Cap so a pathological client can't park a TCP PCB
                    // indefinitely. 30s > browser long-poll window (~20s).
                    if (wait_ms > 30000) wait_ms = 30000;
                } else if (strncmp(p, "stream=1", 8) == 0) {
                    stream = true;
                }
                const char *amp = memchr(p, '&', end - p);
                if (!amp) break;
                p = amp + 1;
            }
        }
    }
    if (!have_since) since = log_buffer_total_written();

    if (stream) {
        // Persistent push. Tell the client the starting cursor in headers,
        // then keep the connection open — http_poll drains new bytes onto
        // the wire each tick. Disable Nagle so a single short log line
        // (≪ MSS) doesn't sit in the send buffer waiting for company.
        //
        // Clamp `since` to current total: after a device reboot the
        // browser may carry an old cursor that's far past the now-zeroed
        // ring counter. Storing that stale value as conn->log_since wedges
        // the stream — http_poll calls log_buffer_read which clamps its
        // local since but never writes back, so conn->log_since stays
        // huge and zero-byte reads spin forever until total catches up.
        uint32_t total = log_buffer_total_written();
        if (since > total) since = total;
        send_log_stream_headers(pcb, since);
        conn->log_since = since;
        conn->state = CONN_STATE_STREAMING;
        altcp_nagle_disable(pcb);
        enable_keepalive(pcb);
        register_streaming(pcb, conn);
        g_streams_started_total++;
        altcp_poll(pcb, http_poll, 1);
        return;
    }

    // If the client asked to wait and there's nothing new, park the
    // connection — the tcp_poll callback will resume it when data arrives
    // or the deadline is reached. tcp_poll fires every `interval` ticks of
    // the lwIP coarse timer (TCP_SLOW_INTERVAL, typically 500ms), so
    // interval=1 gives us ~500ms resolution — fine for interactive logs.
    if (wait_ms > 0 && log_buffer_total_written() == since) {
        conn->log_since = since;
        conn->log_deadline = make_timeout_time_ms(wait_ms);
        conn->state = CONN_STATE_WAITING;
        altcp_poll(pcb, http_poll, 1);
        return;
    }

    send_log_response(pcb, since);
    conn->state = CONN_STATE_DONE;
}

// Send the response headers for /api/data?stream=1. Content is octet-
// stream; body extends to close. X-Data-Cursor hands the client its
// starting byte offset so it can track position across reconnects.
static void send_data_stream_headers(struct altcp_pcb *pcb, uint32_t start_cursor) {
    char hdr[768];
    int hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/octet-stream\r\n"
        "X-Data-Cursor: %u\r\n"
        "Cache-Control: no-store\r\n"
        "X-Accel-Buffering: no\r\n"
        "Connection: close\r\n"
        "%s"
        "Access-Control-Expose-Headers: X-Data-Cursor\r\n"
        "\r\n",
        (unsigned)start_cursor, cors_headers);
    if (hdr_len < 0) hdr_len = 0;
    if (hdr_len > (int)sizeof(hdr)) hdr_len = (int)sizeof(hdr);
    altcp_write(pcb, hdr, hdr_len, TCP_WRITE_FLAG_COPY);
    altcp_output(pcb);
}

// GET /api/data?stream=1[&since=N] — persistent binary push of poe_data
// records. Wire format is documented in data_buffer.h. Unlike /api/log
// this endpoint has no long-poll mode: the browser's parser relies on
// immediate framing recovery at the magic-byte boundary.
static void handle_data(struct altcp_pcb *pcb, http_conn_t *conn) {
    uint32_t since = 0;
    bool have_since = false;
    bool stream = false;
    {
        const char *space = strchr(conn->header_buf, ' ');
        const char *q = space ? strchr(space + 1, '?') : NULL;
        const char *end = space ? strchr(space + 1, ' ') : NULL;
        if (q && end && q < end) {
            const char *p = q + 1;
            while (p < end) {
                if (strncmp(p, "since=", 6) == 0) {
                    since = (uint32_t)strtoul(p + 6, NULL, 10);
                    have_since = true;
                } else if (strncmp(p, "stream=1", 8) == 0) {
                    stream = true;
                }
                const char *amp = memchr(p, '&', end - p);
                if (!amp) break;
                p = amp + 1;
            }
        }
    }
    if (!have_since) since = data_buffer_total_written();

    if (stream) {
        // Clamp `since` to current total — see handle_log for the full
        // explanation of why a stale browser-side cursor would wedge the
        // stream after a device reboot.
        uint32_t total = data_buffer_total_written();
        if (since > total) since = total;
        send_data_stream_headers(pcb, since);
        conn->log_since = since;          // reused field; holds data-ring cursor
        conn->data_stream = true;
        conn->state = CONN_STATE_STREAMING;
        altcp_nagle_disable(pcb);
        enable_keepalive(pcb);
        register_streaming(pcb, conn);
        g_streams_started_total++;
        altcp_poll(pcb, http_poll, 1);
        return;
    }

    // Non-stream: one-shot dump of everything retained since `since`.
    static uint8_t out[4096];
    uint32_t next_cursor = since;
    size_t n = data_buffer_read(since, out, sizeof(out), &next_cursor);
    char hdr[640];
    int hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/octet-stream\r\n"
        "Content-Length: %u\r\n"
        "X-Data-Cursor: %u\r\n"
        "Cache-Control: no-store\r\n"
        "Connection: close\r\n"
        "%s"
        "Access-Control-Expose-Headers: X-Data-Cursor\r\n"
        "\r\n",
        (unsigned)n, (unsigned)next_cursor, cors_headers);
    if (hdr_len < 0) hdr_len = 0;
    if (hdr_len > (int)sizeof(hdr)) hdr_len = (int)sizeof(hdr);
    altcp_write(pcb, hdr, hdr_len, TCP_WRITE_FLAG_COPY);
    if (n > 0) altcp_write(pcb, out, n, TCP_WRITE_FLAG_COPY);
    altcp_output(pcb);
    conn->state = CONN_STATE_DONE;
}

// GET /api/data_schema — returns {"id":"name", …} so the browser can label
// each record stream with a human-readable name when exporting HDF5.
static void handle_data_schema(struct altcp_pcb *pcb, http_conn_t *conn) {
    char body[512];
    size_t n = data_buffer_schema_json(body, sizeof(body));
    send_response(pcb, "200 OK", "application/json", body, n);
    conn->state = CONN_STATE_DONE;
}

static void handle_commit(struct altcp_pcb *pcb, http_conn_t *conn) {
    if (!conn->authenticated) {
        send_error(pcb, "403 Forbidden", "invalid or missing auth token");
        conn->state = CONN_STATE_DONE;
        return;
    }

    ota_commit_result_t r = ota_commit();
    const char *body;
    const char *status;
    switch (r) {
        case OTA_COMMIT_OK:
            status = "200 OK";
            body = "{\"ok\":true,\"committed\":true}";
            break;
        case OTA_COMMIT_NOT_PENDING:
            // Returning 200 on idempotent no-op so retries don't look like
            // a protocol error. The caller can tell by committed=false.
            status = "200 OK";
            body = "{\"ok\":true,\"committed\":false,\"message\":\"not in TBYB mode\"}";
            break;
        case OTA_COMMIT_FAILED:
        default:
            status = "500 Internal Server Error";
            body = "{\"ok\":false,\"error\":\"rom_explicit_buy failed\"}";
            break;
    }
    send_json(pcb, status, body);
    conn->state = CONN_STATE_DONE;
}

// POST /api/cmd?name=<cmd>&<arg>=<val>... — auth-required dispatch into
// the commands module. Reply is JSON: 200 {"ok":true,"result":<obj>} on
// success, 4xx/5xx with {"ok":false,"error":"..."} otherwise.
//
// Args go in the query string to keep the firmware free of a JSON parser
// (matches the /api/log query-string style). Handler-side parsers live
// in commands.c.
static void handle_cmd(struct altcp_pcb *pcb, http_conn_t *conn) {
    if (!conn->authenticated) {
        send_error(pcb, "403 Forbidden", "invalid or missing auth token");
        conn->state = CONN_STATE_DONE;
        return;
    }

    // Locate the query string and pull out name=... up to '&' or path-end.
    const char *space = strchr(conn->header_buf, ' ');
    const char *q = space ? strchr(space + 1, '?') : NULL;
    const char *path_end = space ? strchr(space + 1, ' ') : NULL;
    if (!q || !path_end || q >= path_end) {
        send_error(pcb, "400 Bad Request", "missing query string");
        conn->state = CONN_STATE_DONE;
        return;
    }
    const char *qs = q + 1;
    size_t qs_len = (size_t)(path_end - qs);
    if (qs_len == 0 || qs_len >= 1024) {
        send_error(pcb, "400 Bad Request", "bad query string");
        conn->state = CONN_STATE_DONE;
        return;
    }

    // Snapshot the query string so we can null-terminate it (the request
    // line ends with a space, not a NUL, in the header_buf).
    char qs_buf[1024];
    memcpy(qs_buf, qs, qs_len);
    qs_buf[qs_len] = '\0';

    // Extract `name=<...>` (must be the first or any param).
    char name[64] = {0};
    {
        const char *p = qs_buf;
        while (*p) {
            if (strncmp(p, "name=", 5) == 0) {
                const char *v = p + 5;
                const char *end = strchr(v, '&');
                size_t n = end ? (size_t)(end - v) : strlen(v);
                if (n == 0 || n >= sizeof(name)) break;
                memcpy(name, v, n);
                name[n] = '\0';
                break;
            }
            const char *amp = strchr(p, '&');
            if (!amp) break;
            p = amp + 1;
        }
    }
    if (!name[0]) {
        send_error(pcb, "400 Bad Request", "missing name");
        conn->state = CONN_STATE_DONE;
        return;
    }

    char result[512];
    int written = commands_dispatch(name, qs_buf, result, sizeof(result));

    if (written == -1) {
        send_error(pcb, "404 Not Found", "unknown command");
    } else if (written < 0) {
        // result holds a bare error message. Escape JSON specials so a "
        // or \ in the message can't break the wrapper.
        char esc[256];
        size_t ei = 0;
        for (size_t i = 0; result[i] != '\0' && ei + 2 < sizeof(esc); i++) {
            char c = result[i];
            if (c == '"' || c == '\\') { esc[ei++] = '\\'; esc[ei++] = c; }
            else if ((unsigned char)c < 0x20) { /* drop control chars */ }
            else esc[ei++] = c;
        }
        esc[ei] = '\0';
        char body[320];
        int n = snprintf(body, sizeof(body), "{\"ok\":false,\"error\":\"%s\"}", esc);
        if (n < 0) n = 0;
        // 400 is more honest than 500 for handler-rejected inputs (bad pin,
        // bad value, etc.); the response body carries the precise reason.
        send_response(pcb, "400 Bad Request", "application/json", body, (size_t)n);
    } else {
        // result is the JSON for the "result" field. Wrap it in {ok:true,result:...}.
        char body[640];
        int n = snprintf(body, sizeof(body), "{\"ok\":true,\"result\":%.*s}",
                         (int)((size_t)written < sizeof(result) ? (size_t)written : sizeof(result) - 1),
                         result);
        if (n < 0) n = 0;
        send_response(pcb, "200 OK", "application/json", body, (size_t)n);
    }
    conn->state = CONN_STATE_DONE;
}

// --------------------------------------------------------------------------
// WebSocket Upgrade — GET /api/stream
// --------------------------------------------------------------------------

// RFC 6455 §1.3 — the well-known GUID concatenated with the client's
// Sec-WebSocket-Key before SHA-1 + base64 produces Sec-WebSocket-Accept.
static const char WS_GUID[] = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";

// Lookahead helper: does `value` contain `token` (case-insensitive),
// bounded at the end-of-header (\r). Used for `Connection: Upgrade`
// which may legitimately be "Upgrade", "keep-alive, Upgrade", etc.
static bool header_contains_token(const char *value, const char *token) {
    if (!value || !token) return false;
    size_t tlen = strlen(token);
    while (*value && *value != '\r' && *value != '\n') {
        // skip whitespace + ','
        while (*value == ' ' || *value == ',' || *value == '\t') value++;
        if (strncasecmp(value, token, tlen) == 0) {
            char after = value[tlen];
            if (after == '\0' || after == '\r' || after == '\n' ||
                after == ',' || after == ' ' || after == '\t') {
                return true;
            }
        }
        // advance to next ','
        while (*value && *value != ',' && *value != '\r' && *value != '\n') value++;
    }
    return false;
}

static void handle_ws_upgrade(struct altcp_pcb *pcb, http_conn_t *conn) {
    // Required headers per RFC 6455 §4.1.
    const char *upgrade    = find_header(conn->header_buf, "Upgrade");
    const char *connection = find_header(conn->header_buf, "Connection");
    const char *version    = find_header(conn->header_buf, "Sec-WebSocket-Version");
    const char *key        = find_header(conn->header_buf, "Sec-WebSocket-Key");

    if (!upgrade || strncasecmp(upgrade, "websocket", 9) != 0 ||
        !connection || !header_contains_token(connection, "Upgrade") ||
        !version || version[0] != '1' || version[1] != '3' ||
        !key) {
        send_error(pcb, "400 Bad Request", "websocket upgrade required");
        conn->state = CONN_STATE_DONE;
        return;
    }

    // Snapshot the key (up to its CR/LF).
    char key_val[80];
    size_t key_len = copy_header_value(key, key_val, sizeof(key_val));
    if (key_len == 0 || key_len > 64) {
        send_error(pcb, "400 Bad Request", "bad Sec-WebSocket-Key");
        conn->state = CONN_STATE_DONE;
        return;
    }

    // Compute SHA-1(key + GUID) and base64-encode for the accept token.
    char concat[80 + sizeof(WS_GUID)];
    size_t cat_len = key_len;
    memcpy(concat, key_val, key_len);
    memcpy(concat + cat_len, WS_GUID, sizeof(WS_GUID) - 1);
    cat_len += sizeof(WS_GUID) - 1;

    unsigned char sha[20];
    if (mbedtls_sha1((const unsigned char *)concat, cat_len, sha) != 0) {
        send_error(pcb, "500 Internal Server Error", "sha1 failed");
        conn->state = CONN_STATE_DONE;
        return;
    }
    unsigned char accept_b64[32];
    size_t olen = 0;
    if (mbedtls_base64_encode(accept_b64, sizeof(accept_b64), &olen, sha, sizeof(sha)) != 0) {
        send_error(pcb, "500 Internal Server Error", "base64 failed");
        conn->state = CONN_STATE_DONE;
        return;
    }
    // 28 chars + NUL for a 20-byte SHA-1 input; defensively bound.
    if (olen >= sizeof(accept_b64)) olen = sizeof(accept_b64) - 1;
    accept_b64[olen] = '\0';

    // Build the 101 Switching Protocols response — NO body, NO
    // Content-Length. The bytes are NOT written here; they're passed
    // into ws_server_on_open_with_prefix so the 101 and the first WS
    // NOTICE go out as a SINGLE altcp_write. Under altcp_tls_mbedtls,
    // two back-to-back app-layer writes intermittently get misframed
    // — the browser / ws-probe sees `non-zero RSV bits` rejection on
    // the first WS frame ~40% of the time on fresh handshakes. The
    // single-write coalescing closes that window deterministically.
    char hdr[256];
    int hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.1 101 Switching Protocols\r\n"
        "Upgrade: websocket\r\n"
        "Connection: Upgrade\r\n"
        "Sec-WebSocket-Accept: %s\r\n"
        "\r\n",
        accept_b64);
    if (hdr_len < 0) hdr_len = 0;
    if (hdr_len > (int)sizeof(hdr)) hdr_len = (int)sizeof(hdr);

    // Conn transitions to CONN_STATE_WS. The HTTP header_buf is
    // repurposed as the WS frame reassembly buffer (see ws_server.c's
    // notes on the WS_INGRESS_MAX cap). Register in the streaming
    // registry so a cable drop tears the WS down cleanly.
    //
    // Deliberately NOT enabling TCP keepalive (the legacy /api/log
    // path does). The TCP keepalive idle timer measures time since
    // last RECEIVED packet — for a unidirectional WS stream where
    // the device is the producer and the browser only sends ACKs +
    // an occasional WS PONG, the timer apparently doesn't reset
    // reliably under altcp_tls, so the firmware RSTs the connection
    // every ~50 s (HTTP_KEEP_IDLE_MS + HTTP_KEEP_CNT*HTTP_KEEP_INTVL_MS
    // = 30s + 4×5s) even while data is streaming. Liveness comes
    // from app-layer WS PING/PONG plus the browser's stall watchdog
    // instead. Browser-side close still cleans up via FIN, and
    // http_err / http_server_on_link_down clean up cable-drop cases.
    conn->state = CONN_STATE_WS;
    altcp_nagle_disable(pcb);
    register_streaming(pcb, conn);
    altcp_poll(pcb, http_poll, 1);
    g_streams_started_total++;
    ws_server_on_open_with_prefix(pcb, &conn->ws,
                                  (uint8_t *)conn->header_buf, HTTP_MAX_HEADER,
                                  (const uint8_t *)hdr, (size_t)hdr_len);
}

// --------------------------------------------------------------------------
// HTTP parser
// --------------------------------------------------------------------------

static void parse_request_line(http_conn_t *conn) {
    // Parse method
    if (strncmp(conn->header_buf, "GET ", 4) == 0) {
        conn->method = METHOD_GET;
    } else if (strncmp(conn->header_buf, "POST ", 5) == 0) {
        conn->method = METHOD_POST;
    } else if (strncmp(conn->header_buf, "OPTIONS ", 8) == 0) {
        conn->method = METHOD_OPTIONS;
    }

    // Parse path
    const char *path = strchr(conn->header_buf, ' ');
    if (path) {
        path++; // skip space
        if (strncmp(path, "/api/status", 11) == 0) {
            conn->route = ROUTE_STATUS;
        } else if (strncmp(path, "/api/upload", 11) == 0) {
            conn->route = ROUTE_UPLOAD;
        } else if (strncmp(path, "/api/reboot", 11) == 0) {
            conn->route = ROUTE_REBOOT;
        } else if (strncmp(path, "/api/commit", 11) == 0) {
            conn->route = ROUTE_COMMIT;
        } else if (strncmp(path, "/api/log", 8) == 0) {
            conn->route = ROUTE_LOG;
        } else if (strncmp(path, "/api/data_schema", 16) == 0) {
            // Must be tested before /api/data — it's a prefix.
            conn->route = ROUTE_DATA_SCHEMA;
        } else if (strncmp(path, "/api/data", 9) == 0) {
            conn->route = ROUTE_DATA;
        } else if (strncmp(path, "/api/cmd", 8) == 0) {
            // /api/cmd is not a prefix of /api/commit (mismatch at the 8th
            // char: "cmd" vs "com"), so ordering relative to ROUTE_COMMIT
            // doesn't matter.
            conn->route = ROUTE_CMD;
        } else if (strncmp(path, "/api/incidents", 14) == 0) {
            conn->route = ROUTE_INCIDENTS;
        } else if (strncmp(path, "/api/stream", 11) == 0) {
            conn->route = ROUTE_STREAM;
        }
    }

    // Parse Content-Length
    const char *cl = find_header(conn->header_buf, "Content-Length");
    if (cl) {
        conn->content_length = (uint32_t)strtoul(cl, NULL, 10);
    }

    // Parse chunked-OTA control headers. Value "1" enables. Any other value
    // (or missing header) leaves the flag false.
    const char *ota_start = find_header(conn->header_buf, "X-OTA-Start");
    if (ota_start && ota_start[0] == '1') conn->ota_start = true;
    const char *ota_finish = find_header(conn->header_buf, "X-OTA-Finish");
    if (ota_finish && ota_finish[0] == '1') conn->ota_finish = true;

    // Parse auth token
    const char *token = find_header(conn->header_buf, "X-Auth-Token");
    if (token) {
        char token_val[128];
        copy_header_value(token, token_val, sizeof(token_val));
        // Constant-time comparison to prevent timing attacks
        size_t expected_len = strlen(CONDUIT_AUTH_TOKEN);
        size_t actual_len = strlen(token_val);
        volatile uint8_t result = 0;
        size_t cmp_len = (actual_len < expected_len) ? expected_len : actual_len;
        for (size_t i = 0; i < cmp_len; i++) {
            char a = (i < actual_len) ? token_val[i] : 0;
            char b = (i < expected_len) ? CONDUIT_AUTH_TOKEN[i] : 0;
            result |= a ^ b;
        }
        result |= (actual_len != expected_len);
        conn->authenticated = (result == 0);
    }
}

// --------------------------------------------------------------------------
// TCP callbacks
// --------------------------------------------------------------------------

// Turn on TCP keepalive for streaming connections. Without this, a
// vanished client (browser tab put to sleep, OS VPN drop, NAT box
// reboot — anything that drops packets without sending FIN/RST) holds
// a PCB indefinitely; after MEMP_NUM_TCP_PCB such events the device
// stops accepting new connections even though the firmware is healthy.
// Probes start after KEEP_IDLE_MS of silence, retry every KEEP_INTVL_MS
// up to KEEP_CNT failures → vanished client costs ≈ 50 s before the
// PCB is reaped.
//
// Keepalive lives on the TCP pcb, not the altcp wrapper, so we walk
// the altcp inner_conn chain down to the underlying transport. For
// plain HTTP that's one hop (altcp_tcp's state is the tcp_pcb); for
// HTTPS it's altcp_tls → altcp_tcp → tcp_pcb. A NULL return means
// the wrapper layout doesn't match what we expect (e.g. we're inside
// a different altcp transport in the future); skip keepalive in that
// case rather than blow up.
#define HTTP_KEEP_IDLE_MS   30000
#define HTTP_KEEP_INTVL_MS   5000
#define HTTP_KEEP_CNT           4
static struct tcp_pcb *altcp_to_tcp_pcb(struct altcp_pcb *pcb) {
    while (pcb && pcb->inner_conn) pcb = pcb->inner_conn;
    if (!pcb || !pcb->state) return NULL;
    return (struct tcp_pcb *)pcb->state;
}
static void enable_keepalive(struct altcp_pcb *pcb) {
    struct tcp_pcb *tpcb = altcp_to_tcp_pcb(pcb);
    if (!tpcb) return;
    tpcb->so_options |= SOF_KEEPALIVE;
    tpcb->keep_idle  = HTTP_KEEP_IDLE_MS;
    tpcb->keep_intvl = HTTP_KEEP_INTVL_MS;
    tpcb->keep_cnt   = HTTP_KEEP_CNT;
}

void http_server_on_link_down(void) {
    int aborted = 0;
    for (int i = 0; i < STREAM_REG_SIZE; i++) {
        struct altcp_pcb *pcb = stream_registry[i].pcb;
        http_conn_t   *conn = stream_registry[i].conn;
        if (!pcb) continue;
        // Reap every long-lived conn-pool slot when the link drops past
        // the debounce window. Previously only STREAMING / WS were
        // touched, which meant an OTA mid-upload (CONN_STATE_BODY) or
        // its drain phase (CONN_STATE_DRAINING) or a /api/log long-poll
        // (CONN_STATE_WAITING) would stay in the pool until the TCP
        // keepalive timed it out ~50 s later. The browser's reconnect
        // SYNs got RST'd in that window because the pool was full.
        // CONN_STATE_HEADER is left alone — those are mid-receive of a
        // fresh request and either complete fast or get reaped by the
        // recv-callback's NULL-pbuf path once the FIN/RST arrives.
        // CONN_STATE_DONE is past the response and just waiting for
        // close; also fine to abort but cheap to leave.
        if (conn) {
            if (conn->state != CONN_STATE_STREAMING &&
                conn->state != CONN_STATE_WS &&
                conn->state != CONN_STATE_BODY &&
                conn->state != CONN_STATE_DRAINING &&
                conn->state != CONN_STATE_WAITING) continue;
            // If this slot was mid-upload, abort the OTA cleanly so the
            // ring + flash state aren't left half-applied. Mirrors the
            // same check in conn_close() and http_err().
            if ((conn->state == CONN_STATE_BODY ||
                 conn->state == CONN_STATE_DRAINING) && ota_in_progress()) {
                ota_abort();
            }
        }
        note_stream_close(STREAM_CLOSE_LINK_DOWN, conn);
        // Detach all callbacks BEFORE altcp_abort. lwIP fires the err
        // callback synchronously from inside altcp_abort, and we want
        // it to no-op since we're freeing the conn ourselves below.
        altcp_arg(pcb, NULL);
        altcp_recv(pcb, NULL);
        altcp_err (pcb, NULL);
        altcp_poll(pcb, NULL, 0);
        altcp_abort(pcb);
        if (conn) http_conn_free(conn);
        stream_registry[i].pcb  = NULL;
        stream_registry[i].conn = NULL;
        aborted++;
    }
    if (aborted > 0) {
        DEV_LOG("[http] link-down: aborted %d stream PCB%s\n",
               aborted, aborted == 1 ? "" : "s");
    }
}

static void conn_close(struct altcp_pcb *pcb, http_conn_t *conn) {
    unregister_streaming(pcb, conn);
    if (conn) {
        // If OTA was started but connection dropped mid-body or while
        // the ring was still draining, abort it.
        if ((conn->state == CONN_STATE_BODY || conn->state == CONN_STATE_DRAINING)
            && ota_in_progress()) {
            ota_abort();
        }
        http_conn_free(conn);
    }
    altcp_arg(pcb, NULL);
    altcp_recv(pcb, NULL);
    altcp_err(pcb, NULL);
    altcp_poll(pcb, NULL, 0);  // clears any /api/log long-poll callback
    altcp_close(pcb);
}

// Periodic callback for /api/log long-poll waiters and stream pushers.
// Fires every ~500ms (lwIP TCP coarse timer). Runs on the same tcpip thread
// as http_recv, so accessing conn/pcb without extra locking is safe.
//
//   WAITING:   new bytes OR deadline → flush response and close.
//   STREAMING: as long as bytes are available AND tcp_sndbuf has room,
//              copy a chunk onto the wire and advance log_since. The
//              connection stays open until the client closes (FIN/RST,
//              detected by http_recv with a NULL pbuf).
static err_t http_poll(void *arg, struct altcp_pcb *pcb) {
    g_http_poll_fires++;
    http_conn_t *conn = (http_conn_t *)arg;
    if (!conn) return ERR_OK;

    if (conn->state == CONN_STATE_BODY) {
        // Upload in progress. Peer's window stays closed (we defer all
        // body-byte acks until Core 0 drains) — this is the heartbeat
        // that reopens it. Credit any bytes drained since the last
        // visit so the peer can keep sending at Core 0's rate.
        ota_pump_ack(pcb, conn);
        return ERR_OK;
    }

    if (conn->state == CONN_STATE_DRAINING) {
        // OTA body fully received; Core 0 is draining the ring. Catch
        // up any straggling acks (mostly harmless — peer won't send
        // more — but keeps lwIP's bookkeeping clean), then wait for
        // ota_drain_complete to flip true and finalize.
        ota_pump_ack(pcb, conn);
        if (!ota_drain_complete()) return ERR_OK;
        ota_err_t pump_err = ota_last_pump_error();
        if (pump_err != OTA_OK) {
            send_error(pcb, "422 Unprocessable Entity", ota_error_string(pump_err));
            ota_abort();
            conn->state = CONN_STATE_DONE;
            return ERR_OK;
        }
        ota_err_t fin = ota_finalize_after_drain();
        if (fin != OTA_OK) {
            send_error(pcb, "422 Unprocessable Entity", ota_error_string(fin));
            conn->state = CONN_STATE_DONE;
            return ERR_OK;
        }
        // ota_finalize_after_drain does not return on success — the
        // 200 OK response below is unreachable, but kept defensively.
        send_json(pcb, "200 OK", "{\"ok\":true,\"message\":\"update complete, rebooting\"}");
        conn->state = CONN_STATE_DONE;
        return ERR_OK;
    }

    if (conn->state == CONN_STATE_WAITING) {
        bool has_data = (log_buffer_total_written() != conn->log_since);
        bool timed_out = time_reached(conn->log_deadline);
        if (!has_data && !timed_out) return ERR_OK;
        send_log_response(pcb, conn->log_since);
        conn->state = CONN_STATE_DONE;
        conn_close(pcb, conn);
        return ERR_OK;
    }

    if (conn->state == CONN_STATE_WS) {
        // WebSocket periodic drain. ws_server_poll handles ring drains,
        // app-layer PING, idle keepalive, and status pushes — see
        // ws_server.c for the full policy. The opportunistic flush
        // from http_recv handles sub-100 ms responses; this is the
        // background tick for idle clients.
        ws_server_poll(pcb, &conn->ws);
        return ERR_OK;
    }

    if (conn->state == CONN_STATE_STREAMING) {
        u16_t avail = altcp_sndbuf(pcb);
        if (avail == 0) return ERR_OK;  // wait for ACK; retry next poll
        uint32_t total = conn->data_stream
            ? data_buffer_total_written()
            : log_buffer_total_written();
        bool have_real_data = (total != conn->log_since);
        if (have_real_data) {
            // Sized to absorb a full slow-timer tick of telemetry at 40 KB/s
            // (4 KB per 100 ms) with comfortable headroom for ACK/window
            // dynamics. Smaller buffers force the data ring to backlog and
            // eventually overflow → dropped samples → browser sees voids.
            static uint8_t out[8192];
            size_t cap = (avail < sizeof(out)) ? avail : sizeof(out);
            uint32_t next = conn->log_since;
            size_t n = conn->data_stream
                ? data_buffer_read(conn->log_since, out, cap, &next)
                : log_buffer_read(conn->log_since, out, cap, &next);
            // Always advance log_since to whatever the ring reader resolved
            // to — even on n==0. If conn->log_since was past total (stale
            // browser cursor across a reboot), data_buffer_read clamped its
            // local since to total and returned 0; without writing back, we'd
            // spin here until total caught up to the stale value (~10 minutes
            // at 250 Hz). Pair with the entry-side clamp in handle_data /
            // handle_log so the very first poll already starts at a sane cursor.
            conn->log_since = next;
            if (n == 0) return ERR_OK;
            // Known cosmetic glitch on cable-cycle boundary: ~once per cable
            // cycle the browser receives one log line whose first ~12 bytes
            // are the *previous* line's prefix bytes prepended to the new
            // line, e.g. "[702317801]\t02846190]\ttick=663000…" instead of
            // "[702846190]\ttick=663000…". The duplicated chunk is exactly
            // one prefix-length, suggesting an lwIP TCP segment-pool / pcb-
            // reuse race around abort/reconnect that re-emits the tail of a
            // prior tcp_write. log_since arithmetic on our side is correct
            // (advance-before-write here only causes gaps on ERR_MEM, never
            // duplicates). Proving the lwIP cause needs a wire capture across
            // many cycles; for now we suppress the visible artifact in the
            // browser via a renderer guard in web/console.js (strips a stray
            // "<digits>]\t" tail from the parsed msg). Revisit if the
            // duplication ever exceeds one prefix length.
            err_t e = altcp_write(pcb, out, n, TCP_WRITE_FLAG_COPY);
            if (e == ERR_MEM) return ERR_OK;  // sndbuf race — retry next poll
            if (e != ERR_OK) {
                note_stream_close(STREAM_CLOSE_WRITE_ERR, conn);
                g_stream_last_close_err = e;
                conn->state = CONN_STATE_DONE;
                conn_close(pcb, conn);
                return ERR_OK;
            }
            altcp_output(pcb);
            conn->last_tx_at = get_absolute_time();
            return ERR_OK;
        }

        // No real data. Emit a tiny keepalive when the connection has
        // been silent for STREAM_KEEPALIVE_MS so the browser stall
        // watchdog (1 s HTTP, 4 s HTTPS) sees bytes from a
        // quiet-but-healthy device.
        // For data streams: a 16-byte zero-payload record with a
        // reserved msg_id (CONDUIT_DATA_KEEPALIVE_MSG_ID) — the browser
        // parser skips it before chart/store push.
        // For log streams: a single newline — browser drops empty
        // lines at the top of processLine().
        //
        // Tried a per-conn HTTPS variant (3000 ms over TLS to reduce
        // per-record framing/AEAD CPU on the M33). Caused a hard wedge
        // when combined with the four concurrent conns the IDE opens
        // (telemetry, console, status, upload). Reverted to the
        // unconditional 500 ms — the v10.29 known-good cadence.
        // Revisit only with a real load test of the IDE startup path.
        #define STREAM_KEEPALIVE_MS  500
        if (!time_reached(delayed_by_ms(conn->last_tx_at, STREAM_KEEPALIVE_MS))) {
            return ERR_OK;
        }
        if (conn->data_stream) {
            if (avail < CONDUIT_DATA_RECORD_HEADER) return ERR_OK;
            uint8_t hdr[CONDUIT_DATA_RECORD_HEADER];
            hdr[0] = CONDUIT_DATA_MAGIC;
            hdr[1] = CONDUIT_DATA_VERSION;
            hdr[2] = (uint8_t)(CONDUIT_DATA_KEEPALIVE_MSG_ID & 0xFF);
            hdr[3] = (uint8_t)((CONDUIT_DATA_KEEPALIVE_MSG_ID >> 8) & 0xFF);
            hdr[4] = (uint8_t)CONDUIT_DTYPE_U8;
            hdr[5] = 0; hdr[6] = 0;       // n = 0 (LE u16)
            hdr[7] = 0;                   // reserved
            uint64_t now_us = (uint64_t)to_us_since_boot(get_absolute_time());
            for (int i = 0; i < 8; i++) hdr[8 + i] = (uint8_t)(now_us >> (8 * i));
            err_t e = altcp_write(pcb, hdr, sizeof(hdr), TCP_WRITE_FLAG_COPY);
            if (e == ERR_MEM) return ERR_OK;
            if (e != ERR_OK) {
                note_stream_close(STREAM_CLOSE_WRITE_ERR, conn);
                g_stream_last_close_err = e;
                conn->state = CONN_STATE_DONE;
                conn_close(pcb, conn);
                return ERR_OK;
            }
        } else {
            if (avail < 1) return ERR_OK;
            const char nl = '\n';
            err_t e = altcp_write(pcb, &nl, 1, TCP_WRITE_FLAG_COPY);
            if (e == ERR_MEM) return ERR_OK;
            if (e != ERR_OK) {
                note_stream_close(STREAM_CLOSE_WRITE_ERR, conn);
                g_stream_last_close_err = e;
                conn->state = CONN_STATE_DONE;
                conn_close(pcb, conn);
                return ERR_OK;
            }
        }
        altcp_output(pcb);
        conn->last_tx_at = get_absolute_time();
    }
    return ERR_OK;
}

static err_t http_recv(void *arg, struct altcp_pcb *pcb, struct pbuf *p, err_t err) {
    http_conn_t *conn = (http_conn_t *)arg;

    if (!p || err != ERR_OK) {
        // Connection closed by client
        note_stream_close(p ? STREAM_CLOSE_RECV_ERR : STREAM_CLOSE_RECV_EOF, conn);
        if (err != ERR_OK) g_stream_last_close_err = err;
        conn_close(pcb, conn);
        return ERR_OK;
    }

    if (conn->state == CONN_STATE_DONE
        || conn->state == CONN_STATE_WAITING
        || conn->state == CONN_STATE_STREAMING) {
        // DONE: response already sent, just waiting for FIN.
        // WAITING / STREAMING: /api/log connections are server-driven;
        // discard any extra bytes the client pushes (no pipelined requests).
        altcp_recved(pcb, p->tot_len);
        pbuf_free(p);
        return ERR_OK;
    }

    if (conn->state == CONN_STATE_WS) {
        // WebSocket: feed every byte through the frame codec. The
        // codec dispatches complete CMD/PING/CLOSE frames synchronously
        // on this callback — that's the <100 ms inbound latency path
        // (see ws_server.c). altcp_recved is unconditional: WS flow
        // control is application-layer (PING/PONG + ring-drain pacing
        // in ws_server_poll), not TCP window.
        bool keep_open = true;
        for (struct pbuf *q = p; q != NULL && keep_open; q = q->next) {
            keep_open = ws_server_on_bytes(pcb, &conn->ws,
                                           (uint8_t *)conn->header_buf,
                                           HTTP_MAX_HEADER,
                                           (const uint8_t *)q->payload,
                                           q->len);
        }
        altcp_recved(pcb, p->tot_len);
        pbuf_free(p);
        if (!keep_open) {
            note_stream_close(STREAM_CLOSE_WS_PARSE_FAIL, conn);
            conn->state = CONN_STATE_DONE;
            conn_close(pcb, conn);
        }
        return ERR_OK;
    }

    if (conn->state == CONN_STATE_DRAINING) {
        // Body fully received; trailing bytes (FIN piggybacks, peer-side
        // retransmits) ack immediately. ota_pump_ack continues to credit
        // newly drained ring bytes — without it the connection's window
        // would never reopen if the peer sends one more probe.
        ota_pump_ack(pcb, conn);
        altcp_recved(pcb, p->tot_len);
        pbuf_free(p);
        return ERR_OK;
    }

    // For active-upload conns, credit any bytes Core 0 has drained since
    // the last visit. This is the catch-up path on top of http_poll —
    // each new recv (e.g. a window probe from the peer) is also a chance
    // to advance the advertised window.
    if (conn->state == CONN_STATE_BODY) {
        ota_pump_ack(pcb, conn);
    }

    // `immediate_ack` is the bytes whose receipt is unconditional
    // (headers, non-upload routes' bodies). Upload body bytes do NOT
    // accumulate here — they're acked exclusively via ota_pump_ack,
    // paced to Core 0's drain rate. That's the throttle: peer's window
    // shrinks as it sends, only reopens as Core 0 catches up. Sizing
    // invariant: TCP_WND < OTA_RING_SIZE guarantees the ring can always
    // accept whatever the peer can have in flight.
    size_t immediate_ack = 0;

    // Process data from all pbufs in the chain
    for (struct pbuf *q = p; q != NULL; q = q->next) {
        uint8_t *data = (uint8_t *)q->payload;
        uint16_t len = q->len;

        if (conn->state == CONN_STATE_HEADER) {
            // Accumulate headers
            uint16_t space = HTTP_MAX_HEADER - conn->header_len - 1;
            uint16_t copy = (len < space) ? len : space;
            memcpy(conn->header_buf + conn->header_len, data, copy);
            conn->header_len += copy;
            conn->header_buf[conn->header_len] = '\0';

            // Check for end of headers
            char *hdr_end = strstr(conn->header_buf, "\r\n\r\n");
            if (hdr_end) {
                conn->headers_complete = true;
                parse_request_line(conn);

                // Bytes in THIS pbuf consumed as headers vs trailing body.
                // header_total counts from the start of header_buf, but
                // earlier pbufs may have contributed some of those bytes;
                // what matters here is how many of THIS pbuf's bytes were
                // header (immediate ack) vs body (deferred via pump_ack).
                uint32_t header_total = (hdr_end - conn->header_buf) + 4;
                uint32_t body_in_header = conn->header_len - header_total;
                uint32_t body_in_pbuf = body_in_header < len ? body_in_header : len;
                uint32_t header_in_pbuf = len - body_in_pbuf;
                immediate_ack += header_in_pbuf;

                // Handle the request
                if (conn->method == METHOD_OPTIONS) {
                    send_cors_preflight(pcb);
                    conn->state = CONN_STATE_DONE;
                } else if (conn->method == METHOD_GET && conn->route == ROUTE_STATUS) {
                    handle_status(pcb);
                    conn->state = CONN_STATE_DONE;
                } else if (conn->method == METHOD_POST && conn->route == ROUTE_UPLOAD) {
                    handle_upload_begin(pcb, conn);
                    // If still in BODY state, feed leftover data — NOT
                    // counted into immediate_ack (handled by pump_ack).
                    if (conn->state == CONN_STATE_BODY && body_in_pbuf > 0) {
                        handle_upload_data(pcb, conn,
                            (uint8_t *)(hdr_end + 4), body_in_pbuf);
                    } else {
                        // upload_begin failed (403/409/500): body bytes
                        // that piggybacked were consumed into the header
                        // buf and discarded — ack so the window reopens.
                        immediate_ack += body_in_pbuf;
                    }
                } else if (conn->method == METHOD_POST && conn->route == ROUTE_REBOOT) {
                    handle_reboot(pcb, conn);
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_POST && conn->route == ROUTE_COMMIT) {
                    handle_commit(pcb, conn);
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_GET && conn->route == ROUTE_LOG) {
                    // handle_log sets state to WAITING (long-poll parked) or
                    // DONE (immediate response) — don't force either here.
                    handle_log(pcb, conn);
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_GET && conn->route == ROUTE_DATA) {
                    // handle_data may go to STREAMING or DONE.
                    handle_data(pcb, conn);
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_GET && conn->route == ROUTE_DATA_SCHEMA) {
                    handle_data_schema(pcb, conn);
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_POST && conn->route == ROUTE_CMD) {
                    handle_cmd(pcb, conn);
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_GET && conn->route == ROUTE_INCIDENTS) {
                    handle_incidents_get(pcb);
                    conn->state = CONN_STATE_DONE;
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_POST && conn->route == ROUTE_INCIDENTS) {
                    handle_incidents_post(pcb, conn);
                    conn->state = CONN_STATE_DONE;
                    immediate_ack += body_in_pbuf;
                } else if (conn->method == METHOD_GET && conn->route == ROUTE_STREAM) {
                    // handle_ws_upgrade transitions the conn to
                    // CONN_STATE_WS on success and into CONN_STATE_DONE
                    // on a malformed Upgrade. Either way the request
                    // body (if any) is consumed: WebSocket clients
                    // don't send a body on the Upgrade GET.
                    handle_ws_upgrade(pcb, conn);
                    immediate_ack += body_in_pbuf;
                } else {
                    send_error(pcb, "404 Not Found", "not found");
                    conn->state = CONN_STATE_DONE;
                    immediate_ack += body_in_pbuf;
                }
            } else {
                // headers not yet complete — entire pbuf is header bytes
                immediate_ack += len;
            }
        } else if (conn->state == CONN_STATE_BODY) {
            // Stream body data into the OTA ring. NOT counted into
            // immediate_ack — paced via ota_pump_ack.
            handle_upload_data(pcb, conn, data, len);
        } else {
            // State changed mid-loop (e.g. handler set DONE / DRAINING /
            // WAITING / STREAMING). Remaining bytes are not part of an
            // active body stream — ack so the window stays open.
            immediate_ack += len;
        }
    }

    if (immediate_ack > 0) {
        altcp_recved(pcb, (u16_t)immediate_ack);
    }
    pbuf_free(p);

    if (conn->state == CONN_STATE_DONE) {
        if (conn->keep_alive) {
            // Reset for the next request on the same TCP/TLS pcb. Wipe
            // every per-request field; preserve the pcb-level callbacks
            // (already registered) and the auth-pass, since on a single
            // long upload the same client is doing all chunks.
            conn->state           = CONN_STATE_HEADER;
            conn->method          = METHOD_UNKNOWN;
            conn->route           = ROUTE_UNKNOWN;
            conn->ota_start       = false;
            conn->ota_finish      = false;
            conn->keep_alive      = false;
            conn->content_length  = 0;
            conn->body_received   = 0;
            conn->header_len      = 0;
            conn->headers_complete = false;
            conn->authenticated   = false;
        } else {
            conn_close(pcb, conn);
        }
    }

    return ERR_OK;
}

static void http_err(void *arg, err_t err) {
    http_conn_t *conn = (http_conn_t *)arg;
    // lwIP has already freed the pcb by the time err fires, so we can
    // only match the registry entry by conn pointer.
    unregister_streaming(NULL, conn);
    if (conn) {
        // Bucket by err code so /api/status can attribute "session
        // lasted 22 min then died, no close frame" — every code lands
        // as 1006 in the browser, only the device knows which.
        // ERR_RST  = peer sent RST (router NAT eviction, peer crash)
        // ERR_ABRT = lwIP gave up on its own (TCP retransmit limit hit
        //            after RTO backoff exhausted, OR altcp_tls_mbedtls
        //            internally called altcp_abort after a decrypt /
        //            MAC failure — both pass through here as ERR_ABRT)
        // ERR_CLSD = orderly close that took the err path (rare)
        stream_close_reason_t reason;
        switch (err) {
            case ERR_RST:  reason = STREAM_CLOSE_ERR_RST;   break;
            case ERR_ABRT: reason = STREAM_CLOSE_ERR_ABRT;  break;
            case ERR_CLSD: reason = STREAM_CLOSE_ERR_CLSD;  break;
            default:       reason = STREAM_CLOSE_ERR_OTHER; break;
        }
        note_stream_close(reason, conn);
        g_stream_last_close_err = err;

        // Only abort the OTA if THIS conn is the one streaming it
        // (CONN_STATE_BODY = mid-upload). Without that guard, every
        // unrelated reset connection — failed TLS handshakes, stray
        // browser tabs, ERR_ABRT from PCB pool churn — would nuke an
        // active OTA simply because its err callback fired. Mirror the
        // same check `conn_close` already has. Keep the DEV_LOG so a
        // genuine mid-upload abort still leaves a breadcrumb.
        if ((conn->state == CONN_STATE_BODY || conn->state == CONN_STATE_DRAINING)
            && ota_in_progress()) {
            DEV_LOG("[http] mid-upload conn err=%d → ota_abort\n", err);
            ota_abort();
        }
        http_conn_free(conn);
    }
}

static err_t http_accept(void *arg, struct altcp_pcb *pcb, err_t err) {
    g_accepts_total++;
    if (err != ERR_OK || pcb == NULL) {
        return ERR_VAL;
    }

    // Allocate connection state from the static pool (see
    // http_conn_alloc declaration for why this isn't libc calloc).
    http_conn_t *conn = http_conn_alloc();
    if (!conn) {
        altcp_abort(pcb);
        return ERR_MEM;
    }

    conn->state = CONN_STATE_HEADER;
    conn->opened_at = get_absolute_time();

    altcp_arg(pcb, conn);
    altcp_recv(pcb, http_recv);
    altcp_err(pcb, http_err);

    // Lower priority so network stack stays responsive
    altcp_setprio(pcb, TCP_PRIO_MIN);

    return ERR_OK;
}

// --------------------------------------------------------------------------
// Public API
// --------------------------------------------------------------------------

void http_server_init(void) {
    struct altcp_pcb *pcb = altcp_new(NULL);
    if (!pcb) {
        DEV_LOG("[http] Failed to create PCB\n");
        return;
    }

    err_t err = altcp_bind(pcb, IP_ADDR_ANY, CONDUIT_HTTP_PORT);
    if (err != ERR_OK) {
        DEV_LOG("[http] Bind failed: %d\n", err);
        return;
    }

    pcb = altcp_listen(pcb);
    if (!pcb) {
        DEV_LOG("[http] Listen failed\n");
        return;
    }

    altcp_accept(pcb, http_accept);

    DEV_LOG("[http] Server listening on port %d\n", CONDUIT_HTTP_PORT);
}

bool http_server_init_tls(void) {
    // Per-device TLS server. Reuses every accept/recv/sent/poll/err
    // callback from the plain-HTTP path — all of http_server.c was
    // refactored to the lwIP altcp API so a single set of handlers
    // works for both transports. The only difference here is the
    // pcb constructor (altcp_new with a TLS allocator) and the bind
    // port (CONDUIT_HTTPS_PORT, 443).
    //
    // Caller is responsible for calling conduit_identity_load()
    // before this; we just consume the cached identity.
    const conduit_identity_t *id = conduit_identity_get();
    if (!id) {
        DEV_LOG("[tls] no identity, skipping HTTPS listener\n");
        return false;
    }

    // mbedtls's PEM parser requires the cert buffer to be NUL-terminated
    // with the length INCLUDING the trailing '\0'. Without that, mbedtls
    // falls back to DER parsing and rejects our PEM-encoded chain. The
    // IDENTITY blob stores cert_pem as raw bytes without a NUL (the
    // commission/identity.py encoder pads with 0xFF after the cert), so
    // copy into a NUL-terminated static buffer before handoff. Sized to
    // CONDUIT_IDENTITY_MAX_PAYLOAD which already bounds cert_len in the
    // parser. Static (not stack) so we don't blow the boot stack — and
    // the buffer survives because altcp_tls keeps a parsed copy of the
    // cert internally; we don't need to retain the PEM text.
    static char cert_pem_terminated[CONDUIT_IDENTITY_MAX_PAYLOAD + 1];
    if (id->cert_len > sizeof(cert_pem_terminated) - 1) {
        DEV_LOG("[tls] cert too large: %u > %u\n",
                (unsigned)id->cert_len, (unsigned)(sizeof(cert_pem_terminated) - 1));
        return false;
    }
    memcpy(cert_pem_terminated, id->cert_pem, id->cert_len);
    cert_pem_terminated[id->cert_len] = '\0';

    struct altcp_tls_config *tls_cfg = altcp_tls_create_config_server_privkey_cert(
        id->key_der,  id->key_len,
        NULL, 0,
        (const u8_t *)cert_pem_terminated, id->cert_len + 1);
    // Install our slab allocator AFTER altcp_tls_create_config* — the
    // pico-sdk's altcp_mbedtls_mem_init runs inside that call and sets
    // the hooks to its own tls_malloc/tls_free (lwIP-heap-backed). We
    // override it so mbedtls's per-session 16 KB IN + 8 KB OUT buffers
    // come from fixed static slabs instead, killing the heap
    // fragmentation that wedged HTTPS after ~5 OTA cycles. See
    // mbedtls_slab.h for the full rationale.
    mbedtls_platform_set_calloc_free(conduit_mbedtls_calloc, conduit_mbedtls_free);
    if (!tls_cfg) {
        // Most likely failure modes:
        //   - cert chain has a cert whose pubkey curve isn't enabled in
        //     mbedtls_config.h (LE intermediates use P-384)
        //   - chain has a sig OID whose hash isn't enabled (LE leaf
        //     uses ECDSA-SHA384, intermediate uses RSA-SHA256)
        //   - cert / key parse mismatch (key is for a different cert)
        // Re-add the mbedtls_x509_crt_parse + mbedtls_pk_parse_key probes
        // from git history if you need to pin the exact failure.
        DEV_LOG("[tls] altcp_tls_create_config_server_privkey_cert failed\n");
        return false;
    }

    struct altcp_pcb *pcb = altcp_new(&(altcp_allocator_t){
        .alloc = altcp_tls_alloc,
        .arg   = tls_cfg,
    });
    if (!pcb) {
        DEV_LOG("[tls] altcp_new failed\n");
        return false;
    }

    err_t err = altcp_bind(pcb, IP_ADDR_ANY, CONDUIT_HTTPS_PORT);
    if (err != ERR_OK) {
        DEV_LOG("[tls] bind failed: %d\n", err);
        altcp_close(pcb);
        return false;
    }

    pcb = altcp_listen(pcb);
    if (!pcb) {
        DEV_LOG("[tls] listen failed\n");
        return false;
    }

    altcp_accept(pcb, http_accept);
    DEV_LOG("[tls] HTTPS listening on port %d\n", CONDUIT_HTTPS_PORT);
    return true;
}

void http_server_notify_event(http_event_t event) {
    // Walk the conn pool and mark every active WebSocket so the next
    // ws_server_poll() tick pushes a fresh STATUS snapshot. We don't
    // emit the NOTICE here because that needs altcp_write on the right
    // pcb — and we don't carry pcb pointers in the pool. The poll-time
    // emit picks up state from network_*/ota_* getters which already
    // reflect the new state by the time the caller invokes us.
    //
    // Future-proofing: the event parameter lets us differentiate
    // notice kinds later if a caller wants a kind-specific message.
    (void)event;
    for (int i = 0; i < HTTP_CONN_POOL_SIZE; i++) {
        if (!http_conn_in_use[i]) continue;
        if (http_conn_pool[i].state != CONN_STATE_WS) continue;
        ws_server_mark_status_dirty(&http_conn_pool[i].ws);
    }
}
